/**
 * Caderno de Campo Urbano — estratégia de CRM.
 * A interface traduz estudo em arquitetura de produto, evidência e operação contínua.
 */
import { useState } from "react";
import {
  ArrowDownRight, ArrowUpRight, BookOpenCheck, Check, ChevronRight, Compass,
  Database, FileCheck2, GitBranch, History, LayoutList, MapPinned, Network,
  Radar, ShieldCheck, Sparkles, UsersRound,
} from "lucide-react";

const logo = "/manus-storage/logo-bussola-lote_8c3a6907.png";

const principles = [
  ["01", "Um núcleo, várias jornadas", "Partes, ativos, propostas e evidências formam a mesma linguagem para locação, venda e lotes."],
  ["02", "Relação antes de rótulo", "A mesma pessoa pode ser proprietária, compradora, locatária ou representante em momentos diferentes."],
  ["03", "Evidência antes de certeza", "O CRM registra declarado, recebido, em revisão e próxima ação — sem prometer regularidade automática."],
  ["04", "Território como dado", "Bairro, empreendimento, lote e recorte de mercado são objetos consultáveis, não texto solto."],
  ["05", "Pesquisa com versão", "Toda atualização informa fonte, recorte, período, limitação e impacto antes de virar regra ou painel."],
];

const phases = [
  { n: "0", period: "3–4 semanas", title: "Descoberta e vocabulário", purpose: "Mapear a rotina real de três parceiros-piloto e congelar a primeira versão do modelo canônico.", deliver: ["Mapa de processo de locação, venda e lote", "Dicionário de entidades, estados e papéis", "Linha de base de perdas, pendências e SLA"], gate: "As equipes reconhecem os mesmos estados e palavras para descrever o trabalho." },
  { n: "1", period: "6–8 semanas", title: "Núcleo operacional", purpose: "Construir parte, ativo, perfil de busca, atividade, tarefa e timeline — a rotina diária antes do dossiê complexo.", deliver: ["Fila por responsável e próxima ação", "Captura curta e qualificação progressiva", "Busca territorial e histórico de interações"], gate: "Usuários recuperam contexto sem planilha paralela no fluxo-piloto." },
  { n: "2", period: "6–8 semanas", title: "Proposta e dossiê", purpose: "Conectar ativo, partes, condições, versões, checklist, permissões e trilha de evidência.", deliver: ["Pré-proposta e contraproposta versionadas", "Dossiê por finalidade e cofre documental", "Fila de pendência por função"], gate: "A reabertura documental cai e a proposta preserva seu histórico." },
  { n: "3", period: "8–10 semanas", title: "Loteadora: inventário & carteira", purpose: "Especializar o núcleo para gleba, empreendimento, fase, quadra, lote, alocação, reserva, contrato e recebíveis — sem confundir desenvolvimento urbano com corretagem simples.", deliver: ["Inventário com alocação, restrição e concorrência de estoque", "Tabela, reserva, alçada e contrato de lote versionados", "Plano de pagamento, comprovante, distrato e retorno controlado ao estoque"], gate: "A operação de lote controla estoque e carteira sem planilha paralela nem venda duplicada." },
  { n: "4", period: "4–6 semanas", title: "Inteligência e pesquisa", purpose: "Disponibilizar demanda territorial, evidências de mercado, notas de mudança e impacto de estudo no produto.", deliver: ["Biblioteca de evidências com versão", "Painel de lacunas de carteira", "Calendário de fontes e notas de mudança"], gate: "Gestores usam a pesquisa na revisão de carteira, não só em apresentações." },
];

const updateModes = [
  { key: "guided", title: "Curadoria guiada", tag: "COMEÇO CONTROLADO", text: "A equipe registra uma nova fonte ou estudo, estrutura o recorte e envia para revisão. É a alternativa mais simples para formar disciplina de pesquisa.", trade: "Mais controle editorial; depende de ritual e responsável.", cost: "Baixo", complexity: "Baixa" },
  { key: "periodic", title: "Atualização periódica assistida", tag: "ESCALA COM SUPERVISÃO", text: "Em ciclos definidos, o sistema confere o catálogo de fontes, aponta versões novas e prepara uma ficha para análise humana.", trade: "Reduz tarefas repetitivas; requer manutenção quando fontes mudam formato.", cost: "Moderado", complexity: "Média" },
  { key: "event", title: "Atualização por evento", tag: "BAIXA LATÊNCIA", text: "Quando um emissor oferece um aviso oficial de publicação, a novidade inicia captura e revisão. A viabilidade depende do recurso de cada fonte.", trade: "Mais rápida; exige validação do recurso e uma integração por fonte.", cost: "Variável", complexity: "Média a alta" },
];

const lotLenses = [
  { key: "land", tag: "01 · TERRA & VIABILIDADE", title: "A gleba vem antes do lote.", text: "Aquisição, permuta, cadeia dominial, restrições, estudo técnico, urbano, mercadológico e financeiro. O CRM organiza a decisão; pareceres seguem com os responsáveis habilitados.", steps: ["Gleba e partes relacionadas", "Diligência e restrições", "Estudo de viabilidade versionado"], gate: "Nenhum projeto avança com bloqueio crítico sem parecer e evidência registrados." },
  { key: "approval", tag: "02 · REGISTRO & OBRAS", title: "Venda não substitui registro. Obra não apaga restrição.", text: "Diretriz municipal, aprovação, licença, registro, cronograma, garantia e termo de recebimento caminham em trilhas próprias. Cada documento tem origem, validade e revisor.", steps: ["Regra municipal por vigência", "Registro e matrícula como evidência", "Obra, garantia e aceite"], gate: "O lote só fica comercialmente elegível quando a regra e a evidência aplicáveis estiverem revisadas." },
  { key: "inventory", tag: "03 · ESTOQUE & COMERCIAL", title: "Um lote não pode estar em dois lugares ao mesmo tempo.", text: "Alocação comercial, permutante, garantia municipal e indisponibilidade convivem com disponibilidade, hold, reserva, contrato e reentrada. São estados paralelos, não etiquetas soltas.", steps: ["Quadra, lote e matrícula", "Tabela e alçada versionadas", "Hold, reserva e contrato"], gate: "Reserva incompatível, caucionamento ou alocação de parceiro bloqueiam a venda até liberação explícita." },
  { key: "receivables", tag: "04 · CARTEIRA & PÓS-ENTREGA", title: "A venda gera uma carteira; a carteira mantém a relação viva.", text: "Plano de pagamento, índice contratual, parcela, comprovante, atraso, acordo, distrato, quitação e escritura devem preservar a origem de cada decisão e não virar cálculo opaco.", steps: ["Plano e parcela por versão", "Comprovante e conciliação", "Cobrança, distrato e retorno"], gate: "Nenhum pagamento, distrato ou retorno ao estoque é concluído sem evidência e revisão de caso." },
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }

export default function CrmStrategy() {
  const [phase, setPhase] = useState(0);
  const [mode, setMode] = useState(0);
  const [lotLens, setLotLens] = useState(0);
  const current = phases[phase]; const update = updateModes[mode];
  const lot = lotLenses[lotLens];

  return <div className="site-shell crm-shell">
    <div className="paper-noise" />
    <header className="site-header crm-header">
      <a href="/" className="brand"><img src={logo} alt="Símbolo Bússola de Lote"/><span><b>Observatório</b><small>ESTRATÉGIA CRM</small></span></a>
      <nav><a href="/">Locação</a><a href="/vendas">Vendas & lotes</a><a href="#nucleo">Núcleo</a><a href="#loteadora">Loteadoras</a><a href="#pesquisa">Pesquisa contínua</a></nav>
      <a href="#roteiro" className="nav-cta">Ver roteiro <ArrowDownRight className="h-4 w-4"/></a>
    </header>

    <main id="topo">
      <section className="crm-hero">
        <div className="crm-hero-copy"><Eyebrow>ESTRATÉGIA CONSOLIDADA · CRM IMOBILIÁRIO</Eyebrow><h1>O CRM começa<em>onde o contexto se perde.</em></h1><p>Uma plataforma futura para relacionar pessoas, empresas, ativos, lotes, busca, proposta e evidência — com uma camada viva de pesquisa que evolui sem apagar a origem das decisões.</p><div className="crm-hero-signals"><div><strong>4</strong><span>linhas de negócio<br/>conectadas</span></div><div><strong>1</strong><span>núcleo de dados<br/>canônico</span></div><div><strong>3</strong><span>caminhos de<br/>atualização</span></div></div></div>
        <div className="crm-workbench" aria-label="Mapa do núcleo do CRM"><div className="workbench-top"><span>⌾ MODELO CANÔNICO · V0.1</span><Compass className="h-5 w-5"/></div><div className="workbench-orbit orbit-a"/><div className="workbench-orbit orbit-b"/><div className="workbench-core"><Database className="h-7 w-7"/><b>RELAÇÕES</b><small>partes · ativos<br/>propostas · evidências</small></div><div className="workbench-node node-party"><UsersRound className="h-4 w-4"/>PARTES</div><div className="workbench-node node-asset"><MapPinned className="h-4 w-4"/>ATIVOS</div><div className="workbench-node node-deal"><GitBranch className="h-4 w-4"/>PROPOSTAS</div><div className="workbench-node node-proof"><FileCheck2 className="h-4 w-4"/>EVIDÊNCIAS</div><div className="workbench-foot"><span>declarado</span><i/><span>recebido</span><i/><span>em revisão</span><i/><span>próxima ação</span></div></div>
      </section>

      <section id="nucleo" className="content-section crm-principles"><div className="section-head"><aside><Eyebrow>01 · SISTEMA DE RELAÇÕES</Eyebrow><p>Não é um funil de leads. É uma memória operacional para todo o ciclo imobiliário.</p></aside><div><h2>Uma linguagem para locação, venda e lote — sem fingir que cada jornada é igual.</h2><p>O núcleo reutiliza pessoas, empresas, ativos, território, tarefas, proposta e evidências. As regras específicas surgem na relação entre esses objetos e não em cópias de cadastro.</p></div></div><div className="principle-grid">{principles.map(([n, title, text], index) => <article key={title} className={index === 4 ? "wide" : ""}><code>{n}</code><h3>{title}</h3><p>{text}</p><span>⌾</span></article>)}</div></section>

      <section className="crm-entities"><div className="content-section"><div className="entities-head"><div><Eyebrow>02 · NÚCLEO DE DADOS</Eyebrow><h2>O objeto certo responde à pergunta certa.</h2></div><p>Separar parte, ativo, papel, proposta e documento evita a duplicidade que torna um CRM impossível de confiar. Uma pessoa não é “um lead” para sempre; um imóvel não é apenas um anúncio.</p></div><div className="entity-map"><div className="entity-root"><Network className="h-6 w-6"/><b>WORKSPACE</b><small>organização, unidade, política e acesso</small></div><div className="entity-rail"><article><UsersRound className="h-5 w-5"/><b>PARTY</b><span>pessoa ou empresa</span><small>papel temporal: proprietário, comprador, locatário, representante</small></article><article><MapPinned className="h-5 w-5"/><b>ASSET</b><span>imóvel, unidade ou lote</span><small>território, empreendimento, atributos e estado comercial</small></article><article><GitBranch className="h-5 w-5"/><b>PROPOSAL</b><span>oferta versionada</span><small>partes, valor, condição, vigência, alçada e próximo passo</small></article><article><FileCheck2 className="h-5 w-5"/><b>EVIDENCE</b><span>documento ou declaração</span><small>origem, validade, acesso, revisão e limitação</small></article></div><div className="entity-note"><span>REGRA DE MODELAGEM</span><strong>Relação antes de rótulo.</strong><p>Um vínculo de parte com ativo carrega papel, período e evidência. Assim, copropriedade, empresa, procuração e grupo comprador não criam cópias desgovernadas.</p></div></div></div></section>

      <section id="loteadora" className="crm-lotadora"><div className="content-section"><div className="section-head"><aside><Eyebrow>03 · DOMÍNIO DE LOTEADORA</Eyebrow><p>Loteadora não é venda com lote. É desenvolvimento urbano, estoque com restrições e carteira de recebíveis.</p></aside><div><h2>Da gleba ao pós-entrega, a operação continua quando a venda termina.</h2><p>O produto deve preservar o ciclo de decisão de terra, projeto, registro, infraestrutura, comercialização, carteira e quitação. Cada trilha possui responsável e gate próprios.</p></div></div><div className="lot-market-note"><div><span>RECORTE MG · 1T/2026</span><strong>2.958</strong><small>lotes comercializados na pesquisa setorial</small></div><div><span>VARIAÇÃO DE UNIDADES</span><strong>+40,9%</strong><small>vs. 1T/2025 no mesmo recorte</small></div><div><span>COBERTURA DO ESTUDO</span><strong>57%</strong><small>do potencial de consumo de MG</small></div><p>Unidades e VGV podem se mover em direções diferentes. O painel do CRM deve mostrar cobertura, ticket, tipo de empreendimento e período — não uma única “temperatura” de mercado. <a href="https://sinduscon-mg.org.br/alta-nas-vendas-marca-o-1o-trimestre-de-2026do-mercado-de-loteamentos-em-minas-gerais/" target="_blank" rel="noreferrer">Ver fonte <ArrowUpRight className="h-3 w-3"/></a></p></div><div className="lot-lens"><div className="lot-lens-tabs">{lotLenses.map((item, index) => <button key={item.key} onClick={() => setLotLens(index)} className={lotLens === index ? "active" : ""} aria-pressed={lotLens === index}><code>0{index + 1}</code>{item.title}</button>)}</div><article className="lot-lens-detail"><div><span>{lot.tag}</span><h3>{lot.title}</h3><p>{lot.text}</p></div><ol>{lot.steps.map((step, index) => <li key={step}><code>0{index + 1}</code><span>{step}</span></li>)}</ol><aside><ShieldCheck className="h-5 w-5"/><b>GATE OPERACIONAL</b><p>{lot.gate}</p></aside></article></div><div className="lot-state-strip"><div><b>EMPREENDIMENTO</b><span>viabilidade → aprovação → registrado → obras → vendas → entregue</span></div><div><b>LOTE</b><span>alocação + disponibilidade + registro + carteira em estados paralelos</span></div><div><b>CARTEIRA</b><span>plano → parcela → comprovante → cobrança → distrato/quitação</span></div></div></div></section>

      <section id="roteiro" className="crm-roadmap-section"><div className="content-section"><div className="section-head"><aside><Eyebrow>04 · ROTEIRO DE CONSTRUÇÃO</Eyebrow><p>Desenvolver em ordem de risco: primeiro rotina, depois dossiê, depois inteligência e automação.</p></aside><div><h2>O produto precisa provar uso diário antes de prometer escala.</h2><p>Cada etapa deixa uma entrega observável e um critério de passagem. O desenvolvimento não avança por volume de telas, mas por evidência de que a operação mudou.</p></div></div><div className="crm-roadmap"><div className="crm-phase-list">{phases.map((item, index) => <button key={item.n} onClick={() => setPhase(index)} className={phase === index ? "active" : ""} aria-pressed={phase === index}><code>0{item.n}</code><span><b>{item.title}</b><small>{item.period}</small></span><ChevronRight className="h-4 w-4"/></button>)}</div><article className="crm-phase-detail"><div><span className="kicker">FASE {current.n} · {current.period.toUpperCase()}</span><h3>{current.title}</h3><p>{current.purpose}</p></div><div className="deliverables"><b>ENTREGAS VERIFICÁVEIS</b><ul>{current.deliver.map(item => <li key={item}><Check className="h-4 w-4"/>{item}</li>)}</ul></div><div className="phase-gate"><ShieldCheck className="h-5 w-5"/><span>CRITÉRIO DE PASSAGEM</span><strong>{current.gate}</strong></div></article></div></div></section>

      <section id="pesquisa" className="content-section research-section"><div className="section-head"><aside><Eyebrow>05 · CENTRO DE PESQUISA</Eyebrow><p>A pesquisa não é um relatório perdido: é uma fonte de regra, painel e decisão com versão.</p></aside><div><h2>Atualização contínua sem trocar o passado por um número novo.</h2><p>Cada estudo entra como captura, vira evidência estruturada, passa por revisão e só então pode afetar um painel, uma regra ou um texto operacional. A versão anterior continua visível.</p></div></div><div className="research-flow"><div><BookOpenCheck className="h-5 w-5"/><b>Fonte & snapshot</b><small>origem, data, método e arquivo</small></div><ChevronRight className="h-5 w-5"/><div><Radar className="h-5 w-5"/><b>Evidência</b><small>recorte, valor, limitação e confiança</small></div><ChevronRight className="h-5 w-5"/><div><History className="h-5 w-5"/><b>Revisão</b><small>responsável, parecer e impacto</small></div><ChevronRight className="h-5 w-5"/><div><Sparkles className="h-5 w-5"/><b>Nota de mudança</b><small>regra, painel ou texto versionado</small></div></div><div className="update-board"><div className="update-tabs">{updateModes.map((item, index) => <button key={item.key} onClick={() => setMode(index)} className={mode === index ? "active" : ""}>{item.title}</button>)}</div><article className="update-detail"><span>{update.tag}</span><h3>{update.title}</h3><p>{update.text}</p><div><b>TRADE-OFF</b><p>{update.trade}</p></div><dl><div><dt>CUSTO</dt><dd>{update.cost}</dd></div><div><dt>COMPLEXIDADE</dt><dd>{update.complexity}</dd></div><div><dt>CONTROLE HUMANO</dt><dd>Obrigatório</dd></div></dl></article><aside><Compass className="h-6 w-6"/><b>Não existe escolha automática.</b><p>A alternativa certa depende do volume de fontes, da frequência, do formato do dado e da necessidade de interpretação. Comece com o ciclo que a operação consegue sustentar.</p></aside></div><div className="evidence-ledger"><div><span>PROTOCOLO DE REVISÃO VIVA</span><b>Fonte, interpretação e decisão não são a mesma coisa.</b></div><p>Estudo enviado por parceiro, fonte oficial, dado setorial e observação de piloto recebem classificação, escopo, limitação, confiança, responsável e data de revisão. Se uma evidência divergir, o CRM preserva o conflito e abre uma proposta de mudança — não apaga a versão anterior.</p><div><small>OFICIAL</small><small>SETORIAL</small><small>PARCEIRO</small><small>OPERAÇÃO</small></div></div></section>

      <section className="crm-metrics"><div className="content-section"><div><Eyebrow>06 · PROVA DE VALOR</Eyebrow><h2>Medir a qualidade da operação antes de medir a ambição da plataforma.</h2></div><div className="metric-lanes"><article><span>ROTINA</span><b>tempo até a primeira resposta</b><p>e tarefas que vencem sem próximo passo.</p></article><article><span>QUALIDADE</span><b>completude na etapa certa</b><p>e reaberturas de pendência no dossiê.</p></article><article><span>LOTEADORA</span><b>estoque, carteira e risco separados</b><p>por fase, alocação, praça e condição de pagamento.</p></article><article><span>CONFIANÇA</span><b>acesso e mudança rastreáveis</b><p>em cada documento, proposta e evidência.</p></article></div></div></section>
      <section className="decision crm-decision"><div><Eyebrow>DECISÃO RECOMENDADA</Eyebrow><h2>Começar com o CRM que organiza o trabalho. Deixar a inteligência crescer sobre evidência, não sobre promessa.</h2></div><a href="#roteiro">Explorar etapas <ArrowDownRight className="h-4 w-4"/></a></section>
    </main>
    <footer><div><div className="brand"><img src={logo} alt=""/><span><b>Observatório</b><small>ESTRATÉGIA CRM</small></span></div><p>Estratégia de CRM imobiliário para locação, vendas, construtora, loteadoras e pesquisa contínua.</p></div><div><b>ARTEFATOS DO ESTUDO</b><a className="source-link" href="/">Locação <ArrowUpRight className="h-3 w-3"/></a><a className="source-link" href="/vendas">Vendas & lotes <ArrowUpRight className="h-3 w-3"/></a><a className="source-link" href="#loteadora">Domínio de loteadora <ArrowUpRight className="h-3 w-3"/></a><a className="source-link" href="#pesquisa">Centro de pesquisa <ArrowUpRight className="h-3 w-3"/></a></div><p>O CRM organiza informação e fluxo. Decisões jurídicas, registrais, fiscais e de crédito permanecem nos responsáveis e processos aplicáveis.</p></footer>
  </div>;
}
