import DashboardLayout, { type DashboardAccessGate, type DashboardNavigationItem } from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { isDomainContextReady } from "@/lib/domainFoundationUi";
import { trpc } from "@/lib/trpc";
import { Box, CircleAlert, Compass, LandPlot, Map, ShieldCheck, Workflow } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import "../subdivision-foundation.css";
const nav: DashboardNavigationItem[] = [{ icon: Compass, label: "Central de plataforma", path: "/administracao" }, { icon: LandPlot, label: "Loteadora", path: "/loteadora" }, { icon: Map, label: "Estoque/Mapa de Lotes", path: "/estoque-lotes" }, { icon: Workflow, label: "Vendas Urbanas", path: "/vendas-urbanas" }];
const gate: DashboardAccessGate = { eyebrow: "ESTOQUE/MAPA RESTRITO · CONTEXTO ANTES DE LEITURA", title: "Acesse o cadastro-base de Lotes somente no seu contexto autorizado.", description: "Esta área registra somente posições numeradas em Quadras matrizes de rascunho. O servidor verifica identidade, membership, grant, vigência, finalidade e policy antes de qualquer leitura ou mudança.", routeTitle: "Rota de acesso", routeDetail: "Autenticação → contexto → escopo vigente → policy", actionLabel: "Acessar Estoque/Mapa de Lotes", footerLabel: "LEITURA PROTEGIDA", footerValue: "CONTEXTO · NÃO INFERÊNCIA", footerNote: "Nenhum lote ou registro de outro contexto é exposto antes da autorização.", railTop: "OPERAÇÃO", railBottom: "ESTOQUE" };
export default function LotInventory() {
  const { isAuthenticated } = useAuth(); const [organizationId, setOrganizationId] = useState(""); const [purposeCode, setPurposeCode] = useState("CADASTRO_INICIAL"); const [blockId, setBlockId] = useState(""); const [lotNumber, setLotNumber] = useState(1);
  const context = useMemo(() => ({ organizationId: organizationId.trim(), module: "loteadora" as const, purposeCode: purposeCode.trim().toUpperCase() }), [organizationId, purposeCode]); const ready = isAuthenticated && isDomainContextReady(context) && Boolean(blockId); const queryInput = useMemo(() => ({ ...context, blockId }), [context, blockId]); const lots = trpc.subdivisionFoundation.listDraftLots.useQuery(queryInput, { enabled: ready, retry: false }); const utils = trpc.useUtils();
  const create = trpc.subdivisionFoundation.createDraftLot.useMutation({ onSuccess() { setLotNumber(1); toast.success("Lote em rascunho registrado", { description: "Não cria mapa, disponibilidade, reserva, cliente, contrato ou financeiro." }); void utils.subdivisionFoundation.listDraftLots.invalidate(queryInput); }, onError() { toast.error("Lote não registrado", { description: "O servidor exige Quadra matriz em rascunho no mesmo contexto autorizado." }); } });
  return <DashboardLayout navigationItems={nav} navigationTitle="Núcleo CRM" accessGate={gate}><main className="subdivision-foundation-page"><header className="subdivision-foundation-hero"><div><p className="subdivision-foundation-eyebrow">ESTOQUE/MAPA DE LOTES · CADASTRO-BASE</p><h1>Quadra N · Lote M, sem prometer disponibilidade.</h1><p>O setor separado registra apenas a posição numérica do Lote sob sua Quadra matriz. Não há mapa, área, valor, reserva, cliente, contrato ou financeiro.</p></div><div className="subdivision-foundation-hero__rule"><ShieldCheck size={18}/><span>Rascunho contextual<br/><b>máximo de 100 lotes por Quadra</b></span></div></header><section className="subdivision-foundation-context"><div className="subdivision-foundation-context__fields"><label>Organização<input value={organizationId} onChange={e=>setOrganizationId(e.target.value)} placeholder="UUID da organização"/></label><label>Módulo<input value="Loteadora" readOnly/></label><label>Finalidade<input value={purposeCode} onChange={e=>setPurposeCode(e.target.value.toUpperCase())}/></label></div></section><section className="subdivision-foundation-workspace"><div className="subdivision-foundation-heading"><div><p className="subdivision-foundation-eyebrow">LOTE EM RASCUNHO</p><h2>Uma posição por vez, dentro da Quadra autorizada.</h2></div><p>Informe uma Quadra retornada pelo fluxo protegido de Loteadora. A numeração é de 1 a 100 e única no contexto dessa Quadra.</p></div><form className="subdivision-foundation-card" onSubmit={e=>{e.preventDefault();create.mutate({...context,correlationId:crypto.randomUUID(),blockId,lotNumber})}}><label>ID técnico da Quadra matriz<input value={blockId} onChange={e=>setBlockId(e.target.value)} placeholder="UUID da Quadra autorizada" required/></label><label>Número do Lote<input type="number" min={1} max={100} value={lotNumber} onChange={e=>setLotNumber(Number(e.target.value))} disabled={!ready} required/></label><button disabled={!ready||create.isPending}>{create.isPending?"Registrando Lote":"Registrar Lote em rascunho"}</button></form>{!ready&&<div className="subdivision-foundation-empty"><CircleAlert size={18}/><p>Contexto, sessão e Quadra matriz válida são necessários antes de qualquer leitura ou cadastro.</p></div>}{ready&&lots.data?.map(l=><div className="subdivision-foundation-list__rows" key={l.lotId}><article><span>Lote em rascunho</span><h3>Lote {l.lotNumber}</h3><p>Quadra selecionada · sem estado comercial.</p><code>{l.lotId}</code></article></div>)}</section></main></DashboardLayout>;
}
