import { Building2, CircleAlert, Layers3, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const kindLabels = { condominium: "Condomínio", tower: "Torre", mixed_use: "Uso misto", single_building: "Edificação única", other: "Outra estrutura" } as const;
const phaseLabels = { reference: "Referência", structuring: "Estruturação", review_required: "Revisão necessária" } as const;
type UrbanContext = { organizationId: string; module: "vendas_urbanas"; purposeCode: string };

export function UrbanDevelopmentWorkspace({ context, enabled, active }: { context: UrbanContext; enabled: boolean; active: boolean }) {
  const [internalReference, setInternalReference] = useState("");
  const [developmentKind, setDevelopmentKind] = useState<keyof typeof kindLabels>("condominium");
  const [workingPhase, setWorkingPhase] = useState<keyof typeof phaseLabels>("reference");
  const listQuery = trpc.urbanPipeline.listDraftDevelopments.useQuery(context, { enabled, retry: false });
  const createMutation = trpc.urbanPipeline.createDraftDevelopment.useMutation({ onSuccess: () => { setInternalReference(""); toast.success("Estrutura urbana em rascunho criada", { description: "O rascunho não cria unidades, disponibilidade, preços, proposta, contrato ou financeiro." }); void listQuery.refetch(); }, onError: () => toast.error("Estrutura não criada", { description: "O servidor exige identidade, contexto, grant e finalidade válidos." }) });
  if (!active) return null;
  return <section className="urban-pipeline-link urban-development-workspace" aria-labelledby="urban-development-title">
    <div className="urban-pipeline-heading"><div><p className="urban-pipeline-eyebrow">02A · ESTRUTURA URBANA</p><h2 id="urban-development-title">Defina a matriz do empreendimento antes de unidades ou comercialização.</h2></div><p>O setor registra somente referência interna, tipo de estrutura e fase de trabalho. Não armazena endereço, incorporação, unidades, valores, estoque, corretagem, proposta, contrato ou dados financeiros.</p></div>
    <div className="urban-pipeline-link__grid"><form className="urban-pipeline-card" onSubmit={(event) => { event.preventDefault(); createMutation.mutate({ ...context, correlationId: crypto.randomUUID(), internalReference: internalReference.trim().toUpperCase(), developmentKind, workingPhase }); }}><div className="urban-pipeline-card__title"><Building2 size={19}/><h3>Estrutura em rascunho</h3></div><p>Use um código interno estável. A associação de construtora, torres e unidades será um fluxo posterior, isolado e autorizado.</p><label htmlFor="urban-development-reference">Referência interna<input id="urban-development-reference" value={internalReference} onChange={(event) => setInternalReference(event.target.value.toUpperCase())} placeholder="EX.: TORRE_CENTRAL" disabled={!enabled} minLength={3} maxLength={80} required /></label><label htmlFor="urban-development-kind">Estrutura principal<select id="urban-development-kind" value={developmentKind} onChange={(event) => setDevelopmentKind(event.target.value as keyof typeof kindLabels)} disabled={!enabled}>{Object.entries(kindLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label htmlFor="urban-development-phase">Fase de trabalho<select id="urban-development-phase" value={workingPhase} onChange={(event) => setWorkingPhase(event.target.value as keyof typeof phaseLabels)} disabled={!enabled}>{Object.entries(phaseLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="submit" disabled={!enabled || internalReference.trim().length < 3 || createMutation.isPending}>{createMutation.isPending ? "Registrando rascunho" : "Criar estrutura em rascunho"}</button></form><aside className="urban-pipeline-link__limits" aria-label="Limites da estrutura urbana"><ShieldCheck size={19}/><div><h3>Separação preservada</h3><p>Construtora, correspondente, torres, condomínios e unidades terão cadastros próprios. Este primeiro registro não cria estoque, preço, publicidade, proposta ou qualquer compromisso comercial.</p></div></aside></div>
    {!enabled && <div className="urban-pipeline-empty"><CircleAlert size={18}/><p>Sem contexto autorizado, não há leitura nem criação de estrutura urbana.</p></div>}{enabled && listQuery.isLoading && <div className="urban-pipeline-empty"><span className="urban-pipeline-spinner"/><p>Confirmando o contexto antes da leitura minimizada.</p></div>}{enabled && listQuery.isError && <div className="urban-pipeline-empty is-error"><CircleAlert size={18}/><p>A leitura não foi liberada. Revise identidade, membership, grant, vigência e contexto sem inferir estruturas externas.</p></div>}{enabled && listQuery.data?.length === 0 && <div className="urban-pipeline-empty"><Layers3 size={18}/><p>Nenhuma estrutura em rascunho foi devolvida para este contexto.</p></div>}{enabled && listQuery.data && listQuery.data.length > 0 && <div className="urban-pipeline-list__rows">{listQuery.data.map((item) => <article key={item.developmentId}><span>Estrutura em rascunho</span><h3>{item.internalReference}</h3><p><b>{kindLabels[item.developmentKind]}</b> · {phaseLabels[item.workingPhase]} · criado em {new Date(item.createdAt).toLocaleString("pt-BR")}</p></article>)}</div>}
  </section>;
}
