import { parse as parseCookie } from "cookie";
import type { SupabaseClient } from "@supabase/supabase-js";
import { COOKIE_NAME } from "../shared/const";
import { manageSubdivisionInternalReceivableAlertScheduleInputSchema, type ManageSubdivisionInternalReceivableAlertScheduleInput } from "../shared/subdivisionSaleCaseContracts";
import { createHeartbeatJob, deleteHeartbeatJob, updateHeartbeatJob } from "./_core/heartbeat";
import { getSupabaseAdminClient } from "./supabase";
type RpcClient = Pick<SupabaseClient,"rpc">;
type Heartbeat = { createHeartbeatJob: typeof createHeartbeatJob; updateHeartbeatJob: typeof updateHeartbeatJob; deleteHeartbeatJob: typeof deleteHeartbeatJob };
const schedulePath="/api/scheduled/subdivision-internal-receivable-attention";
function session(cookie:string|undefined){const token=parseCookie(cookie??"")[COOKIE_NAME];if(!token)throw new Error("SUBDIVISION_SCHEDULE_SESSION_REQUIRED");return token;}
async function taskUid(client:RpcClient,name:string,args:Record<string,unknown>){const {data,error}=await client.rpc(name,args);if(error||typeof data!=="string"||!data)throw new Error("SUBDIVISION_RECEIVABLE_ALERT_SCHEDULE_DENIED");return data;}
export async function manageSubdivisionInternalReceivableAlertSchedule(subjectId:string|undefined,raw:ManageSubdivisionInternalReceivableAlertScheduleInput,cookie:string|undefined,client:RpcClient=getSupabaseAdminClient(),heartbeat:Heartbeat={createHeartbeatJob,updateHeartbeatJob,deleteHeartbeatJob}){if(!subjectId)throw new Error("SUBDIVISION_IDENTITY_REQUIRED");const input=manageSubdivisionInternalReceivableAlertScheduleInputSchema.parse(raw);const userSession=session(cookie);const base={p_actor_user_id:subjectId,p_organization_id:input.organizationId,p_module:input.module,p_purpose_code:input.purposeCode,p_correlation_id:input.correlationId}; if(input.action==="activate"){const job=await heartbeat.createHeartbeatJob({name:`subdivision-receivable-attention-${input.organizationId}`,cron:"0 0 8 * * *",path:schedulePath,description:"Lembrete interno diário para o operador revisar vencimentos e cobrar manualmente; sem emissão, envio, banco, baixa ou pagamento."},userSession);try{await client.rpc("subdivision_bind_internal_receivable_alert_schedule",{...base,p_schedule_cron_task_uid:job.taskUid});return{enabled:true,action:"activated" as const};}catch(error){await heartbeat.deleteHeartbeatJob(job.taskUid,userSession).catch(()=>undefined);throw error;}} const actionEnabled=input.action==="resume"; const currentTask=await taskUid(client,input.action==="remove"?"subdivision_unbind_internal_receivable_alert_schedule":"subdivision_set_internal_receivable_alert_schedule_enabled",input.action==="remove"?base:{...base,p_enabled:actionEnabled}); if(input.action==="remove")await heartbeat.deleteHeartbeatJob(currentTask,userSession);else await heartbeat.updateHeartbeatJob(currentTask,{enable:actionEnabled},userSession); return{enabled:actionEnabled,action:input.action};}
