import type { SupabaseClient } from "@supabase/supabase-js";
import { subdivisionContextSchema } from "../shared/subdivisionContracts";
import { createSubdivisionSaleCaseDocumentIntentInputSchema, setSubdivisionSaleCaseDossierReviewInputSchema, type CreateSubdivisionSaleCaseDocumentIntentInput, type SetSubdivisionSaleCaseDossierReviewInput } from "../shared/subdivisionSaleCaseContracts";
import { getSupabaseAdminClient } from "./supabase";
type RpcClient = Pick<SupabaseClient, "rpc">;
const dossierStates = ["awaiting_private_upload", "private_upload_recorded", "review_required", "ready_for_approval"] as const;
export type SaleCaseDossierSummary = { saleCaseId: string; attachmentIntentCount: number; privateUploadCount: number; dossierState: (typeof dossierStates)[number]; reviewReasonPresent: boolean };
const requireSubject = (subjectId: string | undefined) => { if (!subjectId) throw new Error("SUBDIVISION_IDENTITY_REQUIRED"); return subjectId; };
export async function createSubdivisionSaleCaseDocumentIntent(subjectId: string | undefined, rawInput: CreateSubdivisionSaleCaseDocumentIntentInput, client: RpcClient = getSupabaseAdminClient()) { const actorUserId = requireSubject(subjectId); const input = createSubdivisionSaleCaseDocumentIntentInputSchema.parse(rawInput); const { data, error } = await client.rpc("subdivision_create_sale_case_document_intent", { p_actor_user_id: actorUserId, p_organization_id: input.organizationId, p_module: input.module, p_purpose_code: input.purposeCode, p_sale_case_id: input.saleCaseId, p_document_category: input.documentCategory, p_correlation_id: input.correlationId }); if (error || typeof data !== "string") throw new Error("SUBDIVISION_SALE_CASE_DOSSIER_DENIED"); return { attachmentIntentId: data }; }
export async function setSubdivisionSaleCaseDossierReview(subjectId: string | undefined, rawInput: SetSubdivisionSaleCaseDossierReviewInput, client: RpcClient = getSupabaseAdminClient()) { const actorUserId = requireSubject(subjectId); const input = setSubdivisionSaleCaseDossierReviewInputSchema.parse(rawInput); const { data, error } = await client.rpc("subdivision_set_sale_case_dossier_review", { p_actor_user_id: actorUserId, p_organization_id: input.organizationId, p_module: input.module, p_purpose_code: input.purposeCode, p_sale_case_id: input.saleCaseId, p_dossier_ready: input.dossierReady, p_reason_code: input.reasonCode, p_correlation_id: input.correlationId }); if (error || !data || typeof data !== "object" || Array.isArray(data)) throw new Error("SUBDIVISION_SALE_CASE_DOSSIER_REVIEW_DENIED"); return data as { sale_case_id: string; dossier_state: string; human_review_confirmed: boolean }; }
export async function listSubdivisionSaleCaseDossiers(subjectId: string | undefined, rawContext: unknown, client: RpcClient = getSupabaseAdminClient()): Promise<SaleCaseDossierSummary[]> { const actorUserId = requireSubject(subjectId); const context = subdivisionContextSchema.parse(rawContext); const { data, error } = await client.rpc("subdivision_list_sale_case_dossiers", { p_actor_user_id: actorUserId, p_organization_id: context.organizationId, p_module: context.module, p_purpose_code: context.purposeCode }); if (error || !Array.isArray(data)) throw new Error("SUBDIVISION_SALE_CASE_DOSSIER_READ_DENIED"); return data.map(raw => { const row = raw as Record<string, unknown>; const state = String(row.dossier_state); if (!dossierStates.includes(state as SaleCaseDossierSummary["dossierState"])) throw new Error("SUBDIVISION_SALE_CASE_DOSSIER_READ_DENIED"); return { saleCaseId: String(row.sale_case_id), attachmentIntentCount: Number(row.attachment_intent_count), privateUploadCount: Number(row.private_upload_count), dossierState: state as SaleCaseDossierSummary["dossierState"], reviewReasonPresent: row.review_reason_present === true }; }); }
