import type { SupabaseClient } from "@supabase/supabase-js";
import { draftSubdivisionBuyerAttachmentIntentInputSchema, subdivisionContextSchema, type DraftSubdivisionBuyerAttachmentIntentInput } from "../shared/subdivisionContracts";
import { getSupabaseAdminClient } from "./supabase";
type RpcClient = Pick<SupabaseClient, "rpc">;
const attachmentStates = ["awaiting_private_upload", "private_upload_recorded"] as const;
type BuyerAttachmentState = (typeof attachmentStates)[number];
export type BuyerAttachmentIntentSummary = { attachmentIntentId: string; buyerClientId: string; createdAt: string; attachmentState: BuyerAttachmentState };
const requireSubject = (subjectId: string | undefined) => { if (!subjectId) throw new Error("SUBDIVISION_IDENTITY_REQUIRED"); return subjectId; };
export async function createBuyerAttachmentIntent(subjectId: string | undefined, rawInput: DraftSubdivisionBuyerAttachmentIntentInput, client: RpcClient = getSupabaseAdminClient()): Promise<{ attachmentIntentId: string }> { const actorUserId=requireSubject(subjectId);const input=draftSubdivisionBuyerAttachmentIntentInputSchema.parse(rawInput);const {data,error}=await client.rpc("subdivision_create_buyer_attachment_intent",{p_actor_user_id:actorUserId,p_organization_id:input.organizationId,p_module:input.module,p_purpose_code:input.purposeCode,p_buyer_client_id:input.buyerClientId,p_correlation_id:input.correlationId});if(error||typeof data!=="string")throw new Error("SUBDIVISION_ATTACHMENT_INTENT_DENIED");return{attachmentIntentId:data}; }
export async function listBuyerAttachmentIntents(subjectId: string | undefined, rawContext: unknown, client: RpcClient = getSupabaseAdminClient()): Promise<BuyerAttachmentIntentSummary[]> { const actorUserId=requireSubject(subjectId);const context=subdivisionContextSchema.parse(rawContext);const {data,error}=await client.rpc("subdivision_list_buyer_attachment_intents",{p_actor_user_id:actorUserId,p_organization_id:context.organizationId,p_module:context.module,p_purpose_code:context.purposeCode});if(error||!Array.isArray(data))throw new Error("SUBDIVISION_ATTACHMENT_INTENT_READ_DENIED");return data.map((row)=>{const attachmentState=String(row.attachment_state);if(!attachmentStates.includes(attachmentState as BuyerAttachmentState))throw new Error("SUBDIVISION_ATTACHMENT_INTENT_READ_DENIED");return{attachmentIntentId:String(row.attachment_intent_id),buyerClientId:String(row.buyer_client_id),createdAt:String(row.created_at),attachmentState:attachmentState as BuyerAttachmentState};}); }
