import { describe, expect, it, vi } from "vitest";
import { approveSubdivisionSaleCase, releaseSubdivisionInternalReceivableBatch, requestSubdivisionSaleReversal } from "./subdivisionSaleApproval";

const input = { organizationId: "00000000-0000-4000-8000-000000000001", module: "loteadora" as const, purposeCode: "subdivision_sale_preparation", saleCaseId: "00000000-0000-4000-8000-000000000002", correlationId: "00000000-0000-4000-8000-000000000003" };
describe("aprovação material de venda", () => {
  it("aprova o caso, marca somente o estado comercial do lote e informa a liberação interna", async () => { const rpc = vi.fn().mockResolvedValue({ data: { sale_case_id: input.saleCaseId, lot_commercial_state: "sold", contract_state: "approved", internal_batch_released: true, scheduled_item_count: 3 }, error: null }); await expect(approveSubdivisionSaleCase("00000000-0000-4000-8000-000000000004", input, { rpc })).resolves.toMatchObject({ lotCommercialState: "sold", internalBatchReleased: true }); expect(rpc).toHaveBeenCalledWith("subdivision_approve_sale_case", expect.objectContaining({ p_sale_case_id: input.saleCaseId })); });
  it("solicita reversão sem reabrir automaticamente a disponibilidade", async () => { const rpc = vi.fn().mockResolvedValue({ data: { sale_case_id: input.saleCaseId, lot_commercial_state: "reversal_review", contract_state: "approved" }, error: null }); await expect(requestSubdivisionSaleReversal("00000000-0000-4000-8000-000000000004", input, { rpc })).resolves.toMatchObject({ lotCommercialState: "reversal_review" }); expect(rpc).toHaveBeenCalledWith("subdivision_request_sale_reversal", expect.any(Object)); });
  it("libera lote interno somente por RPC contextual depois da aprovação", async () => { const rpc = vi.fn().mockResolvedValue({ data: { sale_case_id: input.saleCaseId, internal_batch_released: true, scheduled_item_count: 3 }, error: null }); await expect(releaseSubdivisionInternalReceivableBatch("00000000-0000-4000-8000-000000000004", input, { rpc })).resolves.toMatchObject({ internalBatchReleased: true, scheduledItemCount: 3 }); expect(rpc).toHaveBeenCalledWith("subdivision_release_internal_receivable_batch", expect.objectContaining({ p_organization_id: input.organizationId, p_sale_case_id: input.saleCaseId, p_correlation_id: input.correlationId })); });
});
