import { CircleAlert, FileStack, Landmark } from "lucide-react";

type Batch = { batchId: string; saleCaseId: string; contractPreparationId: string; batchState: "released_internal_control" | "reversal_review"; itemCount: number; totalCents: number; releasedAt: string; updatedAt: string };

export function SubdivisionInternalReceivableBatchPanel({ isReady, batches, isLoading, isError }: { isReady: boolean; batches: readonly Batch[] | undefined; isLoading: boolean; isError: boolean }) {
  const formatCurrency = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  const stateLabel = (state: Batch["batchState"]) => state === "released_internal_control" ? "Liberado para controle interno" : "Em revisão de reversão";
  return <section className="subdivision-finance-internal" aria-labelledby="subdivision-finance-title">
    <header className="subdivision-finance-internal__head"><div><p className="subdivision-foundation-eyebrow">04 · FINANCEIRO DA LOTEADORA</p><h2 id="subdivision-finance-title">Lotes internos de parcelas liberados.</h2><p>Após uma venda aprovada, a agenda negociada é agrupada para controle do operador. Esta área não emite boleto bancário, não gera linha digitável, não envia cobrança, não acessa banco, não dá baixa e não registra pagamento.</p></div><div className="subdivision-finance-internal__mark"><Landmark size={19} aria-hidden="true" /><span>Controle interno<br /><b>por venda aprovada</b></span></div></header>
    {!isReady ? <div className="subdivision-foundation-empty"><CircleAlert size={18} /><p>Defina um contexto autorizado antes de consultar os lotes internos de parcelas.</p></div> : isLoading ? <div className="subdivision-foundation-empty"><span className="subdivision-foundation-spinner" aria-hidden="true" /><p>Carregando lotes internos autorizados.</p></div> : isError ? <div className="subdivision-foundation-empty is-error"><CircleAlert size={18} /><p>A leitura dos lotes internos não foi liberada para este contexto.</p></div> : !batches?.length ? <div className="subdivision-finance-internal__empty"><FileStack size={21} /><div><b>Nenhum lote interno liberado.</b><span>O lote é criado automaticamente quando uma venda com contrato, agenda e dossiê revisado é aprovada.</span></div></div> : <div className="subdivision-finance-internal__list">{batches.map((batch) => <article key={batch.batchId} data-state={batch.batchState}><div><span>LOTE INTERNO DE PARCELAS</span><b>{stateLabel(batch.batchState)}</b><small>Liberado em {new Date(batch.releasedAt).toLocaleDateString("pt-BR")}</small></div><dl><div><dt>Parcelas</dt><dd>{batch.itemCount}</dd></div><div><dt>Total negociado</dt><dd>{formatCurrency(batch.totalCents)}</dd></div></dl><p>{batch.batchState === "released_internal_control" ? "Disponível para conferência e cobrança manual pelo operador, conforme os prazos da negociação." : "A venda e o lote estão em revisão humana; nenhum lote é apagado, reemitido ou liberado automaticamente."}</p></article>)}</div>}
    <footer className="subdivision-finance-internal__notice"><CircleAlert size={16} aria-hidden="true" /><span>Vencimento é um dado operacional. Ele não confirma atraso, quitação, baixa, pagamento ou cobrança realizada.</span></footer>
  </section>;
}
