-- A237: usa área física já confirmada na matriz somente quando a fonte autorizada não a declarar.
-- Não cria preço, venda, contrato, cobrança, pagamento, repasse ou disponibilidade.

alter table public.subdivision_price_base_policy_lines
  add column if not exists area_provenance text not null default 'source'
  check (area_provenance in ('source', 'matrix_physical'));

create or replace function public.subdivision_preview_price_base_source_v2(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_development_id uuid, p_lines jsonb
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_line_count integer; v_reconciled_count integer; v_unreconciled_count integer; v_matrix_area_resolved_count integer;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if not exists (select 1 from public.subdivision_developments d where d.id = p_development_id and d.organization_id = p_organization_id and d.state = 'draft'::public.party_lifecycle_state) then raise exception using errcode = '42501', message = 'SUBDIVISION_DEVELOPMENT_CONTEXT_DENIED'; end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) not between 1 and 2000 then raise exception using errcode = '22023', message = 'PRICE_BASE_SOURCE_LINES_INVALID'; end if;
  select count(*)::integer into v_line_count from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text);
  if v_line_count <> jsonb_array_length(p_lines) or exists (select 1 from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text) where line.source_row not between 2 and 5000 or line.block_number not between 1 and 999 or line.lot_number not between 1 and 100 or (line.area_sqm is not null and line.area_sqm not between 0.01 and 1000000) or line.base_price_per_sqm_brl not between 0.01 and 1000000000 or line.row_fingerprint !~ '^[a-f0-9]{64}$') or (select count(distinct (line.block_number, line.lot_number)) from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text)) <> v_line_count then raise exception using errcode = '22023', message = 'PRICE_BASE_SOURCE_LINES_INVALID'; end if;
  select count(*)::integer, count(*) filter (where source.area_sqm is null)::integer into v_reconciled_count, v_matrix_area_resolved_count from jsonb_to_recordset(p_lines) as source(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text) join public.subdivision_blocks block on block.organization_id = p_organization_id and block.development_id = p_development_id and block.block_number = source.block_number and block.state = 'draft'::public.party_lifecycle_state join public.subdivision_lots lot on lot.organization_id = p_organization_id and lot.block_id = block.id and lot.lot_number = source.lot_number and lot.state = 'draft'::public.party_lifecycle_state and ((source.area_sqm is not null and lot.area_sqm = source.area_sqm) or (source.area_sqm is null and lot.area_sqm is not null and lot.area_sqm > 0));
  v_unreconciled_count := v_line_count - v_reconciled_count;
  return jsonb_build_object('reconciled_line_count', v_reconciled_count, 'unreconciled_line_count', v_unreconciled_count, 'matrix_area_resolved_line_count', v_matrix_area_resolved_count);
end; $$;

create or replace function public.subdivision_prepare_price_base_policy_v2(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_development_id uuid, p_version_reference text, p_effective_from date, p_source_fingerprint text, p_source_row_count integer, p_exception_count integer, p_lines jsonb, p_correlation_id uuid
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_existing_result jsonb; v_policy_id uuid; v_existing_policy record; v_line_count integer; v_reconciled_count integer; v_matrix_area_resolved_count integer; v_total_exception_count integer; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if not exists (select 1 from public.subdivision_developments d where d.id = p_development_id and d.organization_id = p_organization_id and d.state = 'draft'::public.party_lifecycle_state) then raise exception using errcode = '42501', message = 'SUBDIVISION_DEVELOPMENT_CONTEXT_DENIED'; end if;
  if p_version_reference !~ '^PB_[A-Z0-9_]{3,72}$' or p_effective_from is null or p_source_fingerprint !~ '^[a-f0-9]{64}$' or p_source_row_count not between 1 and 2000 or p_exception_count not between 0 and 2000 or p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) not between 1 and 2000 then raise exception using errcode = '22023', message = 'PRICE_BASE_POLICY_INPUT_INVALID'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text || ':' || p_development_id::text || ':' || trim(upper(p_version_reference)), 0));
  select event.payload_redacted -> 'result' into v_existing_result from public.admin_audit_events event where event.command_name = 'subdivision_prepare_price_base_policy_v2' and event.correlation_id = p_correlation_id and event.actor_user_id = p_actor_user_id and event.organization_id = p_organization_id and event.outcome = 'allowed' order by event.occurred_at desc limit 1;
  if v_existing_result is not null then return v_existing_result; end if;
  select count(*)::integer into v_line_count from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text);
  if v_line_count <> jsonb_array_length(p_lines) or exists (select 1 from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text) where line.source_row not between 2 and 5000 or line.block_number not between 1 and 999 or line.lot_number not between 1 and 100 or (line.area_sqm is not null and line.area_sqm not between 0.01 and 1000000) or line.base_price_per_sqm_brl not between 0.01 and 1000000000 or line.row_fingerprint !~ '^[a-f0-9]{64}$') or (select count(distinct (line.block_number, line.lot_number)) from jsonb_to_recordset(p_lines) as line(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text)) <> v_line_count then raise exception using errcode = '22023', message = 'PRICE_BASE_POLICY_INPUT_INVALID'; end if;
  select count(*)::integer, count(*) filter (where source.area_sqm is null)::integer into v_reconciled_count, v_matrix_area_resolved_count from jsonb_to_recordset(p_lines) as source(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text) join public.subdivision_blocks block on block.organization_id = p_organization_id and block.development_id = p_development_id and block.block_number = source.block_number and block.state = 'draft'::public.party_lifecycle_state join public.subdivision_lots lot on lot.organization_id = p_organization_id and lot.block_id = block.id and lot.lot_number = source.lot_number and lot.state = 'draft'::public.party_lifecycle_state and ((source.area_sqm is not null and lot.area_sqm = source.area_sqm) or (source.area_sqm is null and lot.area_sqm is not null and lot.area_sqm > 0));
  v_total_exception_count := p_exception_count + (v_line_count - v_reconciled_count);
  select id, source_fingerprint, exception_count into v_existing_policy from public.subdivision_price_base_policies where organization_id = p_organization_id and development_id = p_development_id and version_reference = trim(upper(p_version_reference));
  if v_existing_policy.id is not null then if v_existing_policy.source_fingerprint <> p_source_fingerprint or v_existing_policy.exception_count <> v_total_exception_count then raise exception using errcode = '23505', message = 'PRICE_BASE_POLICY_VERSION_CONFLICT'; end if; return jsonb_build_object('policy_id', v_existing_policy.id, 'line_count', v_reconciled_count, 'exception_count', v_total_exception_count); end if;
  insert into public.subdivision_price_base_policies(organization_id, development_id, version_reference, policy_state, effective_from, source_fingerprint, source_row_count, exception_count, created_by) values (p_organization_id, p_development_id, trim(upper(p_version_reference)), 'prepared'::public.subdivision_price_base_policy_state, p_effective_from, p_source_fingerprint, p_source_row_count, v_total_exception_count, p_actor_user_id) returning id into v_policy_id;
  insert into public.subdivision_price_base_policy_lines(organization_id, policy_id, block_id, lot_id, source_area_sqm, base_price_per_sqm_brl, row_fingerprint, area_provenance) select p_organization_id, v_policy_id, block.id, lot.id, coalesce(source.area_sqm, lot.area_sqm), source.base_price_per_sqm_brl, source.row_fingerprint, case when source.area_sqm is null then 'matrix_physical' else 'source' end from jsonb_to_recordset(p_lines) as source(source_row integer, block_number integer, lot_number integer, area_sqm numeric, base_price_per_sqm_brl numeric, row_fingerprint text) join public.subdivision_blocks block on block.organization_id = p_organization_id and block.development_id = p_development_id and block.block_number = source.block_number and block.state = 'draft'::public.party_lifecycle_state join public.subdivision_lots lot on lot.organization_id = p_organization_id and lot.block_id = block.id and lot.lot_number = source.lot_number and lot.state = 'draft'::public.party_lifecycle_state and ((source.area_sqm is not null and lot.area_sqm = source.area_sqm) or (source.area_sqm is null and lot.area_sqm is not null and lot.area_sqm > 0));
  v_result := jsonb_build_object('policy_id', v_policy_id, 'line_count', v_reconciled_count, 'exception_count', v_total_exception_count);
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values (p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_prepare_price_base_policy_v2', 'allowed', 'subdivision_price_base_policy', v_policy_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'source_fingerprint_present', true, 'source_row_count', p_source_row_count, 'line_count', v_reconciled_count, 'exception_count', v_total_exception_count, 'matrix_area_resolved_line_count', v_matrix_area_resolved_count, 'result', v_result));
  return v_result;
end; $$;

revoke all on function public.subdivision_preview_price_base_source_v2(uuid, uuid, public.operating_module, text, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.subdivision_prepare_price_base_policy_v2(uuid, uuid, public.operating_module, text, uuid, text, date, text, integer, integer, jsonb, uuid) from public, anon, authenticated;
grant execute on function public.subdivision_preview_price_base_source_v2(uuid, uuid, public.operating_module, text, uuid, jsonb) to service_role;
grant execute on function public.subdivision_prepare_price_base_policy_v2(uuid, uuid, public.operating_module, text, uuid, text, date, text, integer, integer, jsonb, uuid) to service_role;
