-- A33: componentes de referência de regra econômica; sem beneficiário, valor, percentual, cálculo, parcela, cobrança, pagamento, repasse ou integração externa.
alter table public.subdivision_economic_rule_sets add constraint subdivision_economic_rule_sets_tenant_match unique (id,organization_id);
create table public.subdivision_economic_rule_components (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,economic_rule_set_id uuid not null,component_code text not null check(component_code in ('entry_reference','installment_reference','intermediate_reference','final_result_reference')),working_state text not null check(working_state in ('draft_internal','review_required')),created_by uuid not null references public.identity_subjects(user_id) on delete restrict,created_at timestamptz not null default now(),constraint subdivision_economic_rule_components_rule_set_fk foreign key(economic_rule_set_id,organization_id) references public.subdivision_economic_rule_sets(id,organization_id) on delete restrict,constraint subdivision_economic_rule_components_unique unique(organization_id,economic_rule_set_id,component_code));
alter table public.subdivision_economic_rule_components enable row level security;revoke all on table public.subdivision_economic_rule_components from public,anon,authenticated;
comment on table public.subdivision_economic_rule_components is 'A33: referência estrutural de regras econômicas; sem beneficiário, cálculo, valor, percentual, cobrança, pagamento, repasse ou integração externa.';
create or replace function public.subdivision_create_economic_rule_component(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text,p_economic_rule_set_id uuid,p_component_code text,p_working_state text,p_correlation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare v_existing uuid;v_component_id uuid;begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);select target_id into v_existing from public.admin_audit_events where command_name='subdivision_create_economic_rule_component' and correlation_id=p_correlation_id and outcome='allowed' order by occurred_at desc limit 1;if v_existing is not null then return v_existing;end if;if not exists(select 1 from public.subdivision_economic_rule_sets where id=p_economic_rule_set_id and organization_id=p_organization_id) then raise exception using errcode='42501',message='SUBDIVISION_ECONOMIC_RULE_COMPONENT_CONTEXT_DENIED';end if;insert into public.subdivision_economic_rule_components(organization_id,economic_rule_set_id,component_code,working_state,created_by)values(p_organization_id,p_economic_rule_set_id,p_component_code,p_working_state,p_actor_user_id)on conflict(organization_id,economic_rule_set_id,component_code)do update set working_state=excluded.working_state,created_by=excluded.created_by returning id into v_component_id;insert into public.admin_audit_events(correlation_id,actor_user_id,organization_id,command_name,outcome,target_type,target_id,payload_redacted)values(p_correlation_id,p_actor_user_id,p_organization_id,'subdivision_create_economic_rule_component','allowed','subdivision_economic_rule_component',v_component_id,jsonb_build_object('module',p_module::text,'purpose_code',trim(p_purpose_code),'component_code',p_component_code,'working_state',p_working_state));return v_component_id;end;$$;
revoke all on function public.subdivision_create_economic_rule_component(uuid,uuid,public.operating_module,text,uuid,text,text,uuid) from public,anon,authenticated;grant execute on function public.subdivision_create_economic_rule_component(uuid,uuid,public.operating_module,text,uuid,text,text,uuid) to service_role;
create or replace function public.subdivision_list_economic_rule_components(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(economic_rule_component_id uuid,economic_rule_set_id uuid,component_code text,working_state text,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select id,economic_rule_set_id,component_code,working_state,created_at from public.subdivision_economic_rule_components where organization_id=p_organization_id order by created_at desc;end;$$;
revoke all on function public.subdivision_list_economic_rule_components(uuid,uuid,public.operating_module,text) from public,anon,authenticated;grant execute on function public.subdivision_list_economic_rule_components(uuid,uuid,public.operating_module,text) to service_role;
