-- A64: corrige ambiguidade entre parâmetros de saída e colunas nas leituras minimizadas da Loteadora.
-- Não cria dados, não expõe documentos, financeiro, contratos, valores, percentuais, pagamentos ou repasses.

create or replace function public.subdivision_list_draft_buyer_clients(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(buyer_client_id uuid,party_role_assignment_id uuid,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select buyer_client.id,buyer_client.party_role_assignment_id,buyer_client.created_at from public.subdivision_buyer_clients buyer_client where buyer_client.organization_id=p_organization_id order by buyer_client.created_at desc;end;$$;

create or replace function public.subdivision_list_buyer_attachment_intents(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(attachment_intent_id uuid,buyer_client_id uuid,created_at timestamptz,attachment_state text) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select intent.id,intent.buyer_client_id,intent.created_at,case when intent.storage_key is null then 'awaiting_private_upload' else 'private_upload_recorded' end from public.subdivision_buyer_attachment_intents intent where intent.organization_id=p_organization_id order by intent.created_at desc;end;$$;

create or replace function public.subdivision_list_sale_drafts(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(sale_draft_id uuid,lot_id uuid,buyer_client_id uuid,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select sale_draft.id,sale_draft.lot_id,sale_draft.buyer_client_id,sale_draft.created_at from public.subdivision_sale_drafts sale_draft where sale_draft.organization_id=p_organization_id order by sale_draft.created_at desc;end;$$;

create or replace function public.subdivision_list_sale_draft_work_states(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(sale_draft_work_state_id uuid,sale_draft_id uuid,work_phase text,updated_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select work_state.id,work_state.sale_draft_id,work_state.work_phase,work_state.updated_at from public.subdivision_sale_draft_work_states work_state where work_state.organization_id=p_organization_id order by work_state.updated_at desc;end;$$;

create or replace function public.subdivision_list_sale_draft_co_buyers(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(sale_draft_co_buyer_id uuid,sale_draft_id uuid,buyer_client_id uuid,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select co_buyer.id,co_buyer.sale_draft_id,co_buyer.buyer_client_id,co_buyer.created_at from public.subdivision_sale_draft_co_buyers co_buyer where co_buyer.organization_id=p_organization_id order by co_buyer.created_at desc;end;$$;

create or replace function public.subdivision_list_economic_rule_sets(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(economic_rule_set_id uuid,development_id uuid,version_reference text,working_state text,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select rule_set.id,rule_set.development_id,rule_set.version_reference,rule_set.working_state,rule_set.created_at from public.subdivision_economic_rule_sets rule_set where rule_set.organization_id=p_organization_id order by rule_set.created_at desc;end;$$;

create or replace function public.subdivision_list_economic_rule_components(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(economic_rule_component_id uuid,economic_rule_set_id uuid,component_code text,working_state text,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select component.id,component.economic_rule_set_id,component.component_code,component.working_state,component.created_at from public.subdivision_economic_rule_components component where component.organization_id=p_organization_id order by component.created_at desc;end;$$;

create or replace function public.subdivision_list_economic_rule_component_role_references(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(economic_rule_component_role_reference_id uuid,economic_rule_component_id uuid,internal_party_role_link_id uuid,created_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select role_reference.id,role_reference.economic_rule_component_id,role_reference.internal_party_role_link_id,role_reference.created_at from public.subdivision_economic_rule_component_role_references role_reference where role_reference.organization_id=p_organization_id order by role_reference.created_at desc;end;$$;

revoke all on function public.subdivision_list_draft_buyer_clients(uuid,uuid,public.operating_module,text),public.subdivision_list_buyer_attachment_intents(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_drafts(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_draft_work_states(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_draft_co_buyers(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_sets(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_components(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_component_role_references(uuid,uuid,public.operating_module,text) from public,anon,authenticated;
grant execute on function public.subdivision_list_draft_buyer_clients(uuid,uuid,public.operating_module,text),public.subdivision_list_buyer_attachment_intents(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_drafts(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_draft_work_states(uuid,uuid,public.operating_module,text),public.subdivision_list_sale_draft_co_buyers(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_sets(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_components(uuid,uuid,public.operating_module,text),public.subdivision_list_economic_rule_component_role_references(uuid,uuid,public.operating_module,text) to service_role;
