-- A293: formalização interna do contrato e agenda de parcelas. Não emite boleto, não cobra e não recebe pagamento.

alter table public.subdivision_sale_case_terms add column entry_due_date date null;
alter table public.subdivision_sale_case_terms add constraint subdivision_sale_case_terms_entry_detail check ((coalesce(entry_amount_cents, 0) = 0 and entry_due_date is null) or (coalesce(entry_amount_cents, 0) > 0 and entry_due_date is not null));
drop function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,integer,bigint,date,integer,uuid);
drop function public.subdivision_list_sale_cases(uuid,uuid,public.operating_module,text);

create type public.subdivision_sale_contract_preparation_state as enum ('internal_review', 'approved', 'archived');
create type public.subdivision_sale_receivable_schedule_state as enum ('awaiting_bank_issue', 'archived');
create table public.subdivision_sale_contract_preparations (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict, sale_case_id uuid not null, terms_version integer not null, state public.subdivision_sale_contract_preparation_state not null default 'internal_review', created_by uuid not null references public.identity_subjects(user_id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint subdivision_sale_contract_preparations_tenant_match unique (id, organization_id), constraint subdivision_sale_contract_preparations_case_tenant_fk foreign key (sale_case_id, organization_id) references public.subdivision_sale_cases(id, organization_id) on delete restrict, constraint subdivision_sale_contract_preparations_case_unique unique (organization_id, sale_case_id)
);
alter table public.subdivision_sale_contract_preparations enable row level security; revoke all on table public.subdivision_sale_contract_preparations from public, anon, authenticated;
create table public.subdivision_sale_receivable_schedules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict, contract_preparation_id uuid not null, installment_number integer not null check (installment_number between 0 and 480), installment_kind text not null check (installment_kind in ('entry', 'installment')), due_date date not null, amount_cents bigint not null check (amount_cents between 1 and 100000000000000), bank_issuance_state public.subdivision_sale_receivable_schedule_state not null default 'awaiting_bank_issue', created_by uuid not null references public.identity_subjects(user_id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint subdivision_sale_receivable_schedules_tenant_match unique (id, organization_id), constraint subdivision_sale_receivable_schedules_contract_tenant_fk foreign key (contract_preparation_id, organization_id) references public.subdivision_sale_contract_preparations(id, organization_id) on delete restrict, constraint subdivision_sale_receivable_schedules_item_unique unique (organization_id, contract_preparation_id, installment_number)
);
alter table public.subdivision_sale_receivable_schedules enable row level security; revoke all on table public.subdivision_sale_receivable_schedules from public, anon, authenticated;

create or replace function public.subdivision_save_sale_case_terms(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid, p_negotiated_total_cents bigint, p_entry_amount_cents bigint, p_entry_due_date date, p_installment_count integer, p_installment_amount_cents bigint, p_first_due_date date, p_due_day integer, p_correlation_id uuid
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_idempotent_result jsonb; v_version integer; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_CASE_CONTEXT_DENIED'; end if;
  select event.payload_redacted -> 'result' into v_idempotent_result from public.admin_audit_events event where event.command_name = 'subdivision_save_sale_case_terms' and event.correlation_id = p_correlation_id and event.actor_user_id = p_actor_user_id and event.organization_id = p_organization_id and event.outcome = 'allowed' order by event.occurred_at desc limit 1;
  if v_idempotent_result is not null then return v_idempotent_result; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text || ':' || p_sale_case_id::text, 0));
  if not exists (select 1 from public.subdivision_sale_cases sale_case where sale_case.id = p_sale_case_id and sale_case.organization_id = p_organization_id and sale_case.state = 'preparation') then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_CASE_TERMS_CONTEXT_DENIED'; end if;
  if (coalesce(p_entry_amount_cents, 0) = 0 and p_entry_due_date is not null) or (coalesce(p_entry_amount_cents, 0) > 0 and p_entry_due_date is null) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_ENTRY_DENIED'; end if;
  if (p_installment_count = 0 and (p_installment_amount_cents is not null or p_first_due_date is not null or p_due_day is not null)) or (p_installment_count > 0 and (p_installment_amount_cents is null or p_first_due_date is null or p_due_day is null)) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_INSTALLMENT_DENIED'; end if;
  insert into public.subdivision_sale_case_terms (organization_id, sale_case_id, version_number, negotiated_total_cents, entry_amount_cents, entry_due_date, installment_count, installment_amount_cents, first_due_date, due_day, created_by) values (p_organization_id, p_sale_case_id, 1, p_negotiated_total_cents, p_entry_amount_cents, p_entry_due_date, p_installment_count, p_installment_amount_cents, p_first_due_date, p_due_day, p_actor_user_id) on conflict (organization_id, sale_case_id) do update set version_number = public.subdivision_sale_case_terms.version_number + 1, negotiated_total_cents = excluded.negotiated_total_cents, entry_amount_cents = excluded.entry_amount_cents, entry_due_date = excluded.entry_due_date, installment_count = excluded.installment_count, installment_amount_cents = excluded.installment_amount_cents, first_due_date = excluded.first_due_date, due_day = excluded.due_day, created_by = excluded.created_by, updated_at = now() returning version_number into v_version;
  v_result := jsonb_build_object('sale_case_id', p_sale_case_id, 'terms_version', v_version, 'state', 'preparation');
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_save_sale_case_terms', 'allowed', 'subdivision_sale_case', p_sale_case_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'negotiated_total_present', p_negotiated_total_cents is not null, 'entry_amount_present', p_entry_amount_cents is not null, 'entry_due_date_present', p_entry_due_date is not null, 'installment_count', p_installment_count, 'installment_amount_present', p_installment_amount_cents is not null, 'first_due_date_present', p_first_due_date is not null, 'due_day_present', p_due_day is not null, 'result', v_result));
  return v_result;
end; $$;

create function public.subdivision_formalize_sale_case(p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid, p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_existing uuid; v_contract_id uuid; v_terms record; v_item_count integer; v_total bigint; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_FORMALIZATION_CONTEXT_DENIED'; end if;
  select target_id into v_existing from public.admin_audit_events where command_name = 'subdivision_formalize_sale_case' and correlation_id = p_correlation_id and actor_user_id = p_actor_user_id and organization_id = p_organization_id and outcome = 'allowed' order by occurred_at desc limit 1;
  if v_existing is not null then select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_existing; return jsonb_build_object('contract_preparation_id', v_existing, 'sale_case_id', p_sale_case_id, 'scheduled_item_count', v_item_count, 'bank_issuance_state', 'awaiting_bank_issue'); end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text || ':' || p_sale_case_id::text, 0));
  select terms.* into v_terms from public.subdivision_sale_case_terms terms join public.subdivision_sale_cases sale_case on sale_case.id = terms.sale_case_id and sale_case.organization_id = terms.organization_id where terms.sale_case_id = p_sale_case_id and terms.organization_id = p_organization_id and sale_case.state = 'preparation' for update of terms, sale_case;
  if v_terms.id is null or v_terms.negotiated_total_cents is null then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_FORMALIZATION_TERMS_REQUIRED'; end if;
  v_total := coalesce(v_terms.entry_amount_cents, 0) + coalesce(v_terms.installment_count, 0) * coalesce(v_terms.installment_amount_cents, 0);
  if v_total <> v_terms.negotiated_total_cents or v_total = 0 then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_FORMALIZATION_TOTAL_DENIED'; end if;
  insert into public.subdivision_sale_contract_preparations(organization_id, sale_case_id, terms_version, state, created_by) values(p_organization_id, p_sale_case_id, v_terms.version_number, 'internal_review', p_actor_user_id) on conflict(organization_id, sale_case_id) do update set updated_at = public.subdivision_sale_contract_preparations.updated_at returning id into v_contract_id;
  if not exists (select 1 from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_contract_id) then
    if coalesce(v_terms.entry_amount_cents, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) values(p_organization_id, v_contract_id, 0, 'entry', v_terms.entry_due_date, v_terms.entry_amount_cents, p_actor_user_id); end if;
    if v_terms.installment_count > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) select p_organization_id, v_contract_id, n, 'installment', (v_terms.first_due_date + (n - 1) * interval '1 month')::date, v_terms.installment_amount_cents, p_actor_user_id from generate_series(1, v_terms.installment_count) as n; end if;
  end if;
  select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_contract_id;
  update public.subdivision_sale_cases set state = 'terms_review', updated_at = now() where id = p_sale_case_id and organization_id = p_organization_id;
  v_result := jsonb_build_object('contract_preparation_id', v_contract_id, 'sale_case_id', p_sale_case_id, 'scheduled_item_count', v_item_count, 'bank_issuance_state', 'awaiting_bank_issue');
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_formalize_sale_case', 'allowed', 'subdivision_sale_contract_preparation', v_contract_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'terms_version', v_terms.version_number, 'scheduled_item_count', v_item_count, 'bank_issuance_state', 'awaiting_bank_issue', 'result', v_result));
  return v_result;
end; $$;

create function public.subdivision_list_sale_cases(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text
) returns table (sale_case_id uuid, lot_id uuid, buyer_client_id uuid, state public.subdivision_sale_case_state, terms_version integer, negotiated_total_cents bigint, entry_amount_cents bigint, entry_due_date date, installment_count integer, installment_amount_cents bigint, first_due_date date, due_day integer, created_at timestamptz, updated_at timestamptz)
language plpgsql security definer set search_path = '' as $$
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  return query select sale_case.id, sale_case.lot_id, sale_case.primary_buyer_client_id, sale_case.state, terms.version_number, terms.negotiated_total_cents, terms.entry_amount_cents, terms.entry_due_date, coalesce(terms.installment_count, 0), terms.installment_amount_cents, terms.first_due_date, terms.due_day, sale_case.created_at, sale_case.updated_at from public.subdivision_sale_cases sale_case left join public.subdivision_sale_case_terms terms on terms.sale_case_id = sale_case.id and terms.organization_id = sale_case.organization_id where sale_case.organization_id = p_organization_id and sale_case.state not in ('archived') order by sale_case.updated_at desc, sale_case.id;
end; $$;

create function public.subdivision_list_internal_sale_contracts(p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text) returns table(contract_preparation_id uuid, sale_case_id uuid, contract_state public.subdivision_sale_contract_preparation_state, terms_version integer, scheduled_item_count integer, scheduled_total_cents bigint, bank_issuance_state public.subdivision_sale_receivable_schedule_state, created_at timestamptz, updated_at timestamptz) language plpgsql security definer set search_path = '' as $$
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  return query select contract.id, contract.sale_case_id, contract.state, contract.terms_version, count(schedule.id)::integer, coalesce(sum(schedule.amount_cents), 0)::bigint, coalesce(min(schedule.bank_issuance_state), 'awaiting_bank_issue'::public.subdivision_sale_receivable_schedule_state), contract.created_at, contract.updated_at from public.subdivision_sale_contract_preparations contract left join public.subdivision_sale_receivable_schedules schedule on schedule.contract_preparation_id = contract.id and schedule.organization_id = contract.organization_id and schedule.bank_issuance_state <> 'archived' where contract.organization_id = p_organization_id and contract.state <> 'archived' group by contract.id order by contract.updated_at desc, contract.id;
end; $$;
revoke all on function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,date,integer,bigint,date,integer,uuid), public.subdivision_formalize_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_list_internal_sale_contracts(uuid,uuid,public.operating_module,text) from public, anon, authenticated;
grant execute on function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,date,integer,bigint,date,integer,uuid), public.subdivision_formalize_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_list_internal_sale_contracts(uuid,uuid,public.operating_module,text) to service_role;
