-- A305: composição interna de entrada, parcelas, venda à vista, complemento e bem entregue.
-- Controle interno somente: não emite boleto, não acessa banco, não envia mensagens, não dá baixa e não registra pagamentos.

alter table public.subdivision_sale_case_terms
  add column settlement_mode text not null default 'structured' check (settlement_mode in ('cash', 'structured')),
  add column entry_installment_count integer not null default 0 check (entry_installment_count between 0 and 480),
  add column entry_installment_amount_cents bigint null check (entry_installment_amount_cents between 1 and 100000000000000),
  add column entry_first_due_date date null,
  add column entry_due_day integer null check (entry_due_day between 1 and 31),
  add column cash_settlement_amount_cents bigint null check (cash_settlement_amount_cents between 1 and 100000000000000),
  add column cash_settlement_due_date date null,
  add column supplemental_amount_cents bigint null check (supplemental_amount_cents between 1 and 100000000000000),
  add column supplemental_due_date date null,
  add column trade_in_credit_cents bigint null check (trade_in_credit_cents between 1 and 100000000000000),
  add column trade_in_due_date date null,
  add column trade_in_category text null check (trade_in_category is null or trade_in_category ~ '^[a-z][a-z0-9_]{2,47}$'),
  add column trade_in_description text null check (trade_in_description is null or char_length(trade_in_description) between 3 and 240);

alter table public.subdivision_sale_receivable_schedules drop constraint subdivision_sale_receivable_schedules_installment_kind_check;
alter table public.subdivision_sale_receivable_schedules add constraint subdivision_sale_receivable_schedules_installment_kind_check check (installment_kind in ('entry', 'entry_installment', 'installment', 'cash_settlement', 'supplemental_cash', 'trade_in_credit'));
alter table public.subdivision_sale_receivable_schedules drop constraint subdivision_sale_receivable_schedules_item_unique;
alter table public.subdivision_sale_receivable_schedules add constraint subdivision_sale_receivable_schedules_item_unique unique (organization_id, contract_preparation_id, installment_kind, installment_number);

alter table public.subdivision_internal_receivable_batch_items add column schedule_kind text not null default 'installment';
update public.subdivision_internal_receivable_batch_items item set schedule_kind = schedule.installment_kind from public.subdivision_sale_receivable_schedules schedule where schedule.id = item.schedule_id and schedule.organization_id = item.organization_id;
alter table public.subdivision_internal_receivable_batch_items drop constraint subdivision_internal_receivable_batch_items_number_unique;
alter table public.subdivision_internal_receivable_batch_items add constraint subdivision_internal_receivable_batch_items_number_unique unique (organization_id, batch_id, schedule_kind, item_number);

drop function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,date,integer,bigint,date,integer,uuid);
drop function public.subdivision_list_sale_cases(uuid,uuid,public.operating_module,text);

create or replace function public.subdivision_save_sale_case_terms(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid,
  p_negotiated_total_cents bigint, p_entry_amount_cents bigint, p_entry_due_date date,
  p_entry_installment_count integer, p_entry_installment_amount_cents bigint, p_entry_first_due_date date, p_entry_due_day integer,
  p_installment_count integer, p_installment_amount_cents bigint, p_first_due_date date, p_due_day integer,
  p_settlement_mode text, p_cash_settlement_amount_cents bigint, p_cash_settlement_due_date date,
  p_supplemental_amount_cents bigint, p_supplemental_due_date date,
  p_trade_in_credit_cents bigint, p_trade_in_due_date date, p_trade_in_category text, p_trade_in_description text,
  p_correlation_id uuid
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_idempotent_result jsonb; v_version integer; v_result jsonb; v_composed_total bigint;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_CASE_CONTEXT_DENIED'; end if;
  select event.payload_redacted -> 'result' into v_idempotent_result from public.admin_audit_events event where event.command_name = 'subdivision_save_sale_case_terms' and event.correlation_id = p_correlation_id and event.actor_user_id = p_actor_user_id and event.organization_id = p_organization_id and event.outcome = 'allowed' order by event.occurred_at desc limit 1;
  if v_idempotent_result is not null then return v_idempotent_result; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text || ':' || p_sale_case_id::text, 0));
  if not exists (select 1 from public.subdivision_sale_cases sale_case where sale_case.id = p_sale_case_id and sale_case.organization_id = p_organization_id and sale_case.state = 'preparation') then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_CASE_TERMS_CONTEXT_DENIED'; end if;
  if p_negotiated_total_cents is null or p_negotiated_total_cents <= 0 or p_settlement_mode not in ('cash', 'structured') or coalesce(p_entry_amount_cents, 0) < 0 or coalesce(p_entry_installment_count, 0) not between 0 and 480 or coalesce(p_installment_count, 0) not between 0 and 480 then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_VALUE_DENIED'; end if;
  if (coalesce(p_entry_amount_cents, 0) = 0 and p_entry_due_date is not null) or (coalesce(p_entry_amount_cents, 0) > 0 and p_entry_due_date is null) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_ENTRY_DENIED'; end if;
  if (coalesce(p_entry_installment_count, 0) = 0 and (p_entry_installment_amount_cents is not null or p_entry_first_due_date is not null or p_entry_due_day is not null)) or (coalesce(p_entry_installment_count, 0) > 0 and (p_entry_installment_amount_cents is null or p_entry_first_due_date is null or p_entry_due_day is null or extract(day from p_entry_first_due_date)::integer <> p_entry_due_day)) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_ENTRY_INSTALLMENT_DENIED'; end if;
  if (coalesce(p_installment_count, 0) = 0 and (p_installment_amount_cents is not null or p_first_due_date is not null or p_due_day is not null)) or (coalesce(p_installment_count, 0) > 0 and (p_installment_amount_cents is null or p_first_due_date is null or p_due_day is null or extract(day from p_first_due_date)::integer <> p_due_day)) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_INSTALLMENT_DENIED'; end if;
  if (coalesce(p_cash_settlement_amount_cents, 0) = 0 and p_cash_settlement_due_date is not null) or (coalesce(p_cash_settlement_amount_cents, 0) > 0 and p_cash_settlement_due_date is null) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_CASH_DENIED'; end if;
  if (coalesce(p_supplemental_amount_cents, 0) = 0 and p_supplemental_due_date is not null) or (coalesce(p_supplemental_amount_cents, 0) > 0 and p_supplemental_due_date is null) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_SUPPLEMENTAL_DENIED'; end if;
  if (coalesce(p_trade_in_credit_cents, 0) = 0 and (p_trade_in_due_date is not null or p_trade_in_category is not null or p_trade_in_description is not null)) or (coalesce(p_trade_in_credit_cents, 0) > 0 and (p_trade_in_due_date is null or p_trade_in_category is null or p_trade_in_description is null)) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_TRADE_IN_DENIED'; end if;
  if coalesce(p_entry_installment_count, 0) + coalesce(p_installment_count, 0) > 480 then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_SCHEDULE_LIMIT_DENIED'; end if;
  if p_settlement_mode = 'cash' and (coalesce(p_cash_settlement_amount_cents, 0) = 0 or coalesce(p_entry_amount_cents, 0) > 0 or coalesce(p_entry_installment_count, 0) > 0 or coalesce(p_installment_count, 0) > 0) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_MODE_DENIED'; end if;
  if p_settlement_mode = 'structured' and (coalesce(p_cash_settlement_amount_cents, 0) > 0 or (coalesce(p_entry_amount_cents, 0) = 0 and coalesce(p_entry_installment_count, 0) = 0 and coalesce(p_installment_count, 0) = 0)) then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_MODE_DENIED'; end if;
  v_composed_total := coalesce(p_entry_amount_cents, 0) + coalesce(p_entry_installment_count, 0) * coalesce(p_entry_installment_amount_cents, 0) + coalesce(p_installment_count, 0) * coalesce(p_installment_amount_cents, 0) + coalesce(p_cash_settlement_amount_cents, 0) + coalesce(p_supplemental_amount_cents, 0) + coalesce(p_trade_in_credit_cents, 0);
  if v_composed_total <> p_negotiated_total_cents then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_CASE_TERMS_TOTAL_DENIED'; end if;
  insert into public.subdivision_sale_case_terms (organization_id, sale_case_id, version_number, negotiated_total_cents, entry_amount_cents, entry_due_date, entry_installment_count, entry_installment_amount_cents, entry_first_due_date, entry_due_day, installment_count, installment_amount_cents, first_due_date, due_day, settlement_mode, cash_settlement_amount_cents, cash_settlement_due_date, supplemental_amount_cents, supplemental_due_date, trade_in_credit_cents, trade_in_due_date, trade_in_category, trade_in_description, created_by) values (p_organization_id, p_sale_case_id, 1, p_negotiated_total_cents, p_entry_amount_cents, p_entry_due_date, p_entry_installment_count, p_entry_installment_amount_cents, p_entry_first_due_date, p_entry_due_day, p_installment_count, p_installment_amount_cents, p_first_due_date, p_due_day, p_settlement_mode, p_cash_settlement_amount_cents, p_cash_settlement_due_date, p_supplemental_amount_cents, p_supplemental_due_date, p_trade_in_credit_cents, p_trade_in_due_date, p_trade_in_category, p_trade_in_description, p_actor_user_id) on conflict (organization_id, sale_case_id) do update set version_number = public.subdivision_sale_case_terms.version_number + 1, negotiated_total_cents = excluded.negotiated_total_cents, entry_amount_cents = excluded.entry_amount_cents, entry_due_date = excluded.entry_due_date, entry_installment_count = excluded.entry_installment_count, entry_installment_amount_cents = excluded.entry_installment_amount_cents, entry_first_due_date = excluded.entry_first_due_date, entry_due_day = excluded.entry_due_day, installment_count = excluded.installment_count, installment_amount_cents = excluded.installment_amount_cents, first_due_date = excluded.first_due_date, due_day = excluded.due_day, settlement_mode = excluded.settlement_mode, cash_settlement_amount_cents = excluded.cash_settlement_amount_cents, cash_settlement_due_date = excluded.cash_settlement_due_date, supplemental_amount_cents = excluded.supplemental_amount_cents, supplemental_due_date = excluded.supplemental_due_date, trade_in_credit_cents = excluded.trade_in_credit_cents, trade_in_due_date = excluded.trade_in_due_date, trade_in_category = excluded.trade_in_category, trade_in_description = excluded.trade_in_description, created_by = excluded.created_by, updated_at = now() returning version_number into v_version;
  v_result := jsonb_build_object('sale_case_id', p_sale_case_id, 'terms_version', v_version, 'state', 'preparation');
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_save_sale_case_terms', 'allowed', 'subdivision_sale_case', p_sale_case_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'settlement_mode', p_settlement_mode, 'entry_cash_present', coalesce(p_entry_amount_cents, 0) > 0, 'entry_installment_count', coalesce(p_entry_installment_count, 0), 'installment_count', coalesce(p_installment_count, 0), 'cash_settlement_present', coalesce(p_cash_settlement_amount_cents, 0) > 0, 'supplemental_present', coalesce(p_supplemental_amount_cents, 0) > 0, 'trade_in_present', coalesce(p_trade_in_credit_cents, 0) > 0, 'total_reconciled', true, 'result', v_result));
  return v_result;
end; $$;

create function public.subdivision_list_sale_cases(
  p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text
) returns table (sale_case_id uuid, lot_id uuid, buyer_client_id uuid, state public.subdivision_sale_case_state, terms_version integer, negotiated_total_cents bigint, entry_amount_cents bigint, entry_due_date date, entry_installment_count integer, entry_installment_amount_cents bigint, entry_first_due_date date, entry_due_day integer, installment_count integer, installment_amount_cents bigint, first_due_date date, due_day integer, settlement_mode text, cash_settlement_amount_cents bigint, cash_settlement_due_date date, supplemental_amount_cents bigint, supplemental_due_date date, trade_in_credit_cents bigint, trade_in_due_date date, trade_in_category text, trade_in_description text, created_at timestamptz, updated_at timestamptz)
language plpgsql security definer set search_path = '' as $$
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_CASE_CONTEXT_DENIED'; end if;
  return query select sale_case.id, sale_case.lot_id, sale_case.primary_buyer_client_id, sale_case.state, terms.version_number, terms.negotiated_total_cents, terms.entry_amount_cents, terms.entry_due_date, coalesce(terms.entry_installment_count, 0), terms.entry_installment_amount_cents, terms.entry_first_due_date, terms.entry_due_day, coalesce(terms.installment_count, 0), terms.installment_amount_cents, terms.first_due_date, terms.due_day, terms.settlement_mode, terms.cash_settlement_amount_cents, terms.cash_settlement_due_date, terms.supplemental_amount_cents, terms.supplemental_due_date, terms.trade_in_credit_cents, terms.trade_in_due_date, terms.trade_in_category, terms.trade_in_description, sale_case.created_at, sale_case.updated_at from public.subdivision_sale_cases sale_case left join public.subdivision_sale_case_terms terms on terms.sale_case_id = sale_case.id and terms.organization_id = sale_case.organization_id where sale_case.organization_id = p_organization_id and sale_case.state <> 'archived' order by sale_case.updated_at desc, sale_case.id;
end; $$;

create or replace function public.subdivision_formalize_sale_case(p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid, p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_existing uuid; v_contract_id uuid; v_terms record; v_item_count integer; v_total bigint; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_FORMALIZATION_CONTEXT_DENIED'; end if;
  select target_id into v_existing from public.admin_audit_events where command_name = 'subdivision_formalize_sale_case' and correlation_id = p_correlation_id and actor_user_id = p_actor_user_id and organization_id = p_organization_id and outcome = 'allowed' order by occurred_at desc limit 1;
  if v_existing is not null then select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_existing; return jsonb_build_object('contract_preparation_id', v_existing, 'sale_case_id', p_sale_case_id, 'scheduled_item_count', v_item_count, 'bank_issuance_state', 'awaiting_bank_issue'); end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text || ':' || p_sale_case_id::text, 0));
  select terms.* into v_terms from public.subdivision_sale_case_terms terms join public.subdivision_sale_cases sale_case on sale_case.id = terms.sale_case_id and sale_case.organization_id = terms.organization_id where terms.sale_case_id = p_sale_case_id and terms.organization_id = p_organization_id and sale_case.state = 'preparation' for update of terms, sale_case;
  if v_terms.id is null or v_terms.negotiated_total_cents is null then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_FORMALIZATION_TERMS_REQUIRED'; end if;
  v_total := coalesce(v_terms.entry_amount_cents, 0) + coalesce(v_terms.entry_installment_count, 0) * coalesce(v_terms.entry_installment_amount_cents, 0) + coalesce(v_terms.installment_count, 0) * coalesce(v_terms.installment_amount_cents, 0) + coalesce(v_terms.cash_settlement_amount_cents, 0) + coalesce(v_terms.supplemental_amount_cents, 0) + coalesce(v_terms.trade_in_credit_cents, 0);
  if v_total <> v_terms.negotiated_total_cents or v_total = 0 then raise exception using errcode = '22023', message = 'SUBDIVISION_SALE_FORMALIZATION_TOTAL_DENIED'; end if;
  insert into public.subdivision_sale_contract_preparations(organization_id, sale_case_id, terms_version, state, created_by) values(p_organization_id, p_sale_case_id, v_terms.version_number, 'internal_review', p_actor_user_id) on conflict(organization_id, sale_case_id) do update set updated_at = public.subdivision_sale_contract_preparations.updated_at returning id into v_contract_id;
  if not exists (select 1 from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_contract_id) then
    if coalesce(v_terms.entry_amount_cents, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) values(p_organization_id, v_contract_id, 0, 'entry', v_terms.entry_due_date, v_terms.entry_amount_cents, p_actor_user_id); end if;
    if coalesce(v_terms.entry_installment_count, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) select p_organization_id, v_contract_id, n, 'entry_installment', case when n = 1 then v_terms.entry_first_due_date else pg_catalog.make_date(extract(year from (pg_catalog.date_trunc('month', v_terms.entry_first_due_date::timestamp) + (n - 1) * interval '1 month'))::integer, extract(month from (pg_catalog.date_trunc('month', v_terms.entry_first_due_date::timestamp) + (n - 1) * interval '1 month'))::integer, least(v_terms.entry_due_day, extract(day from (pg_catalog.date_trunc('month', v_terms.entry_first_due_date::timestamp) + n * interval '1 month - 1 day'))::integer)) end, v_terms.entry_installment_amount_cents, p_actor_user_id from generate_series(1, v_terms.entry_installment_count) as n; end if;
    if coalesce(v_terms.installment_count, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) select p_organization_id, v_contract_id, n, 'installment', case when n = 1 then v_terms.first_due_date else pg_catalog.make_date(extract(year from (pg_catalog.date_trunc('month', v_terms.first_due_date::timestamp) + (n - 1) * interval '1 month'))::integer, extract(month from (pg_catalog.date_trunc('month', v_terms.first_due_date::timestamp) + (n - 1) * interval '1 month'))::integer, least(v_terms.due_day, extract(day from (pg_catalog.date_trunc('month', v_terms.first_due_date::timestamp) + n * interval '1 month - 1 day'))::integer)) end, v_terms.installment_amount_cents, p_actor_user_id from generate_series(1, v_terms.installment_count) as n; end if;
    if coalesce(v_terms.cash_settlement_amount_cents, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) values(p_organization_id, v_contract_id, 0, 'cash_settlement', v_terms.cash_settlement_due_date, v_terms.cash_settlement_amount_cents, p_actor_user_id); end if;
    if coalesce(v_terms.supplemental_amount_cents, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) values(p_organization_id, v_contract_id, 0, 'supplemental_cash', v_terms.supplemental_due_date, v_terms.supplemental_amount_cents, p_actor_user_id); end if;
    if coalesce(v_terms.trade_in_credit_cents, 0) > 0 then insert into public.subdivision_sale_receivable_schedules(organization_id, contract_preparation_id, installment_number, installment_kind, due_date, amount_cents, created_by) values(p_organization_id, v_contract_id, 0, 'trade_in_credit', v_terms.trade_in_due_date, v_terms.trade_in_credit_cents, p_actor_user_id); end if;
  end if;
  select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules where organization_id = p_organization_id and contract_preparation_id = v_contract_id;
  update public.subdivision_sale_cases set state = 'terms_review', updated_at = now() where id = p_sale_case_id and organization_id = p_organization_id;
  v_result := jsonb_build_object('contract_preparation_id', v_contract_id, 'sale_case_id', p_sale_case_id, 'scheduled_item_count', v_item_count, 'bank_issuance_state', 'awaiting_bank_issue');
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_formalize_sale_case', 'allowed', 'subdivision_sale_contract_preparation', v_contract_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'terms_version', v_terms.version_number, 'scheduled_item_count', v_item_count, 'total_reconciled', true, 'result', v_result));
  return v_result;
end; $$;

create or replace function public.subdivision_approve_sale_case(p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid, p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_idempotent jsonb; v_case record; v_contract_id uuid; v_batch_id uuid; v_item_count integer; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_APPROVAL_CONTEXT_DENIED'; end if;
  select event.payload_redacted -> 'result' into v_idempotent from public.admin_audit_events event where event.command_name = 'subdivision_approve_sale_case' and event.correlation_id = p_correlation_id and event.actor_user_id = p_actor_user_id and event.organization_id = p_organization_id and event.outcome = 'allowed' order by event.occurred_at desc limit 1;
  if v_idempotent is not null then return v_idempotent; end if;
  select sale_case.* into v_case from public.subdivision_sale_cases sale_case where sale_case.id = p_sale_case_id and sale_case.organization_id = p_organization_id for update;
  if v_case.id is null or v_case.state <> 'terms_review' then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_APPROVAL_STATE_DENIED'; end if;
  if not exists (select 1 from public.subdivision_sale_case_dossier_reviews review where review.sale_case_id = p_sale_case_id and review.organization_id = p_organization_id and review.dossier_state = 'ready_for_approval') then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_APPROVAL_DOSSIER_DENIED'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text || ':' || v_case.lot_id::text, 0));
  select contract.id into v_contract_id from public.subdivision_sale_contract_preparations contract where contract.sale_case_id = p_sale_case_id and contract.organization_id = p_organization_id and contract.state = 'internal_review' for update;
  if v_contract_id is null then raise exception using errcode = '42501', message = 'SUBDIVISION_SALE_APPROVAL_CONTRACT_DENIED'; end if;
  select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules schedule where schedule.organization_id = p_organization_id and schedule.contract_preparation_id = v_contract_id and schedule.bank_issuance_state <> 'archived';
  if v_item_count = 0 then raise exception using errcode = '42501', message = 'SUBDIVISION_INTERNAL_BATCH_SCHEDULE_DENIED'; end if;
  insert into public.subdivision_internal_receivable_batches(organization_id, sale_case_id, contract_preparation_id, batch_state, released_by) values(p_organization_id, p_sale_case_id, v_contract_id, 'released_internal_control', p_actor_user_id) on conflict(organization_id, contract_preparation_id) do update set updated_at = public.subdivision_internal_receivable_batches.updated_at returning id into v_batch_id;
  insert into public.subdivision_internal_receivable_batch_items(organization_id, batch_id, schedule_id, item_number, schedule_kind, due_date, amount_cents) select p_organization_id, v_batch_id, schedule.id, row_number() over (order by schedule.due_date, schedule.installment_kind, schedule.installment_number)::integer, schedule.installment_kind, schedule.due_date, schedule.amount_cents from public.subdivision_sale_receivable_schedules schedule where schedule.organization_id = p_organization_id and schedule.contract_preparation_id = v_contract_id and schedule.bank_issuance_state <> 'archived' on conflict(organization_id, schedule_id) do nothing;
  update public.subdivision_sale_contract_preparations set state = 'approved', updated_at = now() where id = v_contract_id and organization_id = p_organization_id;
  update public.subdivision_sale_cases set state = 'approved', updated_at = now() where id = p_sale_case_id and organization_id = p_organization_id;
  insert into public.subdivision_lot_commercial_states(organization_id, lot_id, sale_case_id, commercial_state, created_by) values (p_organization_id, v_case.lot_id, p_sale_case_id, 'sold', p_actor_user_id) on conflict(organization_id, lot_id) do update set sale_case_id = excluded.sale_case_id, commercial_state = 'sold', created_by = excluded.created_by, updated_at = now();
  v_result := jsonb_build_object('sale_case_id', p_sale_case_id, 'lot_commercial_state', 'sold', 'contract_state', 'approved', 'internal_batch_released', true, 'scheduled_item_count', v_item_count);
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_approve_sale_case', 'allowed', 'subdivision_sale_case', p_sale_case_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'lot_commercial_state', 'sold', 'contract_state', 'approved', 'dossier_reviewed', true, 'internal_batch_released', true, 'scheduled_item_count', v_item_count, 'result', v_result));
  return v_result;
end; $$;

create or replace function public.subdivision_release_internal_receivable_batch(p_actor_user_id uuid, p_organization_id uuid, p_module public.operating_module, p_purpose_code text, p_sale_case_id uuid, p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_idempotent jsonb; v_contract_id uuid; v_batch_id uuid; v_item_count integer; v_result jsonb;
begin
  perform private.require_active_subdivision_draft_authority(p_actor_user_id, p_organization_id, p_module, p_purpose_code);
  if p_module <> 'loteadora' then raise exception using errcode = '42501', message = 'SUBDIVISION_INTERNAL_BATCH_CONTEXT_DENIED'; end if;
  select event.payload_redacted -> 'result' into v_idempotent from public.admin_audit_events event where event.command_name = 'subdivision_release_internal_receivable_batch' and event.correlation_id = p_correlation_id and event.actor_user_id = p_actor_user_id and event.organization_id = p_organization_id and event.outcome = 'allowed' order by event.occurred_at desc limit 1;
  if v_idempotent is not null then return v_idempotent; end if;
  select contract.id into v_contract_id from public.subdivision_sale_contract_preparations contract join public.subdivision_sale_cases sale_case on sale_case.id = contract.sale_case_id and sale_case.organization_id = contract.organization_id where contract.sale_case_id = p_sale_case_id and contract.organization_id = p_organization_id and contract.state = 'approved' and sale_case.state = 'approved' for update of contract, sale_case;
  if v_contract_id is null then raise exception using errcode = '42501', message = 'SUBDIVISION_INTERNAL_BATCH_APPROVAL_DENIED'; end if;
  select count(*)::integer into v_item_count from public.subdivision_sale_receivable_schedules schedule where schedule.organization_id = p_organization_id and schedule.contract_preparation_id = v_contract_id and schedule.bank_issuance_state <> 'archived';
  if v_item_count = 0 then raise exception using errcode = '42501', message = 'SUBDIVISION_INTERNAL_BATCH_SCHEDULE_DENIED'; end if;
  insert into public.subdivision_internal_receivable_batches(organization_id, sale_case_id, contract_preparation_id, batch_state, released_by) values(p_organization_id, p_sale_case_id, v_contract_id, 'released_internal_control', p_actor_user_id) on conflict(organization_id, contract_preparation_id) do update set updated_at = public.subdivision_internal_receivable_batches.updated_at returning id into v_batch_id;
  insert into public.subdivision_internal_receivable_batch_items(organization_id, batch_id, schedule_id, item_number, schedule_kind, due_date, amount_cents) select p_organization_id, v_batch_id, schedule.id, row_number() over (order by schedule.due_date, schedule.installment_kind, schedule.installment_number)::integer, schedule.installment_kind, schedule.due_date, schedule.amount_cents from public.subdivision_sale_receivable_schedules schedule where schedule.organization_id = p_organization_id and schedule.contract_preparation_id = v_contract_id and schedule.bank_issuance_state <> 'archived' on conflict(organization_id, schedule_id) do nothing;
  v_result := jsonb_build_object('sale_case_id', p_sale_case_id, 'internal_batch_released', true, 'scheduled_item_count', v_item_count);
  insert into public.admin_audit_events(correlation_id, actor_user_id, organization_id, command_name, outcome, target_type, target_id, payload_redacted) values(p_correlation_id, p_actor_user_id, p_organization_id, 'subdivision_release_internal_receivable_batch', 'allowed', 'subdivision_internal_receivable_batch', v_batch_id, jsonb_build_object('module', p_module::text, 'purpose_code', trim(p_purpose_code), 'internal_batch_released', true, 'scheduled_item_count', v_item_count, 'result', v_result));
  return v_result;
end; $$;

revoke all on function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,date,integer,bigint,date,integer,integer,bigint,date,integer,text,bigint,date,bigint,date,bigint,date,text,text,uuid), public.subdivision_list_sale_cases(uuid,uuid,public.operating_module,text), public.subdivision_formalize_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_approve_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_release_internal_receivable_batch(uuid,uuid,public.operating_module,text,uuid,uuid) from public, anon, authenticated;
grant execute on function public.subdivision_save_sale_case_terms(uuid,uuid,public.operating_module,text,uuid,bigint,bigint,date,integer,bigint,date,integer,integer,bigint,date,integer,text,bigint,date,bigint,date,bigint,date,text,text,uuid), public.subdivision_list_sale_cases(uuid,uuid,public.operating_module,text), public.subdivision_formalize_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_approve_sale_case(uuid,uuid,public.operating_module,text,uuid,uuid), public.subdivision_release_internal_receivable_batch(uuid,uuid,public.operating_module,text,uuid,uuid) to service_role;
