-- A21: papéis internos temporais; não define participação econômica, contrato, login, portal, cobrança ou repasse.
alter type public.party_role_kind add value if not exists 'shareholder';
alter type public.party_role_kind add value if not exists 'partner';
alter type public.party_role_kind add value if not exists 'land_contributor';
create table public.subdivision_internal_party_roles (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,development_id uuid not null,party_role_assignment_id uuid not null,created_by uuid not null references public.identity_subjects(user_id) on delete restrict,created_at timestamptz not null default now(),constraint subdivision_internal_roles_development_fk foreign key(development_id,organization_id) references public.subdivision_developments(id,organization_id) on delete restrict,constraint subdivision_internal_roles_assignment_fk foreign key(party_role_assignment_id,organization_id) references public.party_role_assignments(id,organization_id) on delete restrict,constraint subdivision_internal_roles_unique unique(organization_id,development_id,party_role_assignment_id));
alter table public.subdivision_internal_party_roles enable row level security;revoke all on table public.subdivision_internal_party_roles from public,anon,authenticated;
comment on table public.subdivision_internal_party_roles is 'A21: vínculo interno de papel temporal de sócio, parceiro ou cedente de terra; sem percentual, valor, contrato, login, portal, cobrança ou repasse.';
create or replace function public.subdivision_link_draft_internal_party_role(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text,p_development_id uuid,p_party_role_assignment_id uuid,p_correlation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare v_existing uuid;v_id uuid;begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);select target_id into v_existing from public.admin_audit_events where command_name='subdivision_link_draft_internal_party_role' and correlation_id=p_correlation_id and outcome='allowed' order by occurred_at desc limit 1;if v_existing is not null then return v_existing;end if;if not exists(select 1 from public.subdivision_developments where id=p_development_id and organization_id=p_organization_id and state='draft') or not exists(select 1 from public.party_role_assignments where id=p_party_role_assignment_id and organization_id=p_organization_id and module='loteadora' and state='draft' and role::text in ('shareholder','partner','land_contributor')) then raise exception using errcode='42501',message='SUBDIVISION_INTERNAL_ROLE_CONTEXT_DENIED';end if;insert into public.subdivision_internal_party_roles(organization_id,development_id,party_role_assignment_id,created_by)values(p_organization_id,p_development_id,p_party_role_assignment_id,p_actor_user_id) on conflict(organization_id,development_id,party_role_assignment_id) do update set created_by=excluded.created_by returning id into v_id;insert into public.admin_audit_events(correlation_id,actor_user_id,organization_id,command_name,outcome,target_type,target_id,payload_redacted)values(p_correlation_id,p_actor_user_id,p_organization_id,'subdivision_link_draft_internal_party_role','allowed','subdivision_internal_party_role',v_id,jsonb_build_object('module',p_module::text,'purpose_code',trim(p_purpose_code),'role_linked',true));return v_id;end;$$;
create or replace function public.subdivision_list_draft_internal_party_roles(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(link_id uuid,development_id uuid,party_role_assignment_id uuid,role public.party_role_kind,starts_at timestamptz,ends_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select l.id,l.development_id,l.party_role_assignment_id,a.role,a.starts_at,a.ends_at from public.subdivision_internal_party_roles l join public.subdivision_developments d on d.id=l.development_id and d.organization_id=l.organization_id join public.party_role_assignments a on a.id=l.party_role_assignment_id and a.organization_id=l.organization_id where l.organization_id=p_organization_id and d.state='draft' and a.state='draft' order by l.created_at desc;end;$$;
revoke all on function public.subdivision_link_draft_internal_party_role(uuid,uuid,public.operating_module,text,uuid,uuid,uuid),public.subdivision_list_draft_internal_party_roles(uuid,uuid,public.operating_module,text) from public,anon,authenticated;grant execute on function public.subdivision_link_draft_internal_party_role(uuid,uuid,public.operating_module,text,uuid,uuid,uuid),public.subdivision_list_draft_internal_party_roles(uuid,uuid,public.operating_module,text) to service_role;
