-- A29: classificação interna de trabalho; não é reserva, proposta, contrato, preço, cobrança ou financeiro.
alter table public.subdivision_sale_drafts add constraint subdivision_sale_drafts_tenant_match unique (id,organization_id);
create table public.subdivision_sale_draft_work_states (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,sale_draft_id uuid not null,work_phase text not null check(work_phase in ('link_review','attachment_review','human_review')),updated_by uuid not null references public.identity_subjects(user_id) on delete restrict,updated_at timestamptz not null default now(),constraint subdivision_sale_draft_work_states_draft_fk foreign key(sale_draft_id,organization_id) references public.subdivision_sale_drafts(id,organization_id) on delete restrict,constraint subdivision_sale_draft_work_states_unique unique(organization_id,sale_draft_id));
alter table public.subdivision_sale_draft_work_states enable row level security;revoke all on table public.subdivision_sale_draft_work_states from public,anon,authenticated;
comment on table public.subdivision_sale_draft_work_states is 'A29: estado interno de trabalho para rascunho de venda; não determina disponibilidade, reserva, proposta, contrato ou financeiro.';
create or replace function public.subdivision_upsert_sale_draft_work_state(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text,p_sale_draft_id uuid,p_work_phase text,p_correlation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare v_existing uuid;v_state_id uuid;begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);select target_id into v_existing from public.admin_audit_events where command_name='subdivision_upsert_sale_draft_work_state' and correlation_id=p_correlation_id and outcome='allowed' order by occurred_at desc limit 1;if v_existing is not null then return v_existing;end if;if not exists(select 1 from public.subdivision_sale_drafts where id=p_sale_draft_id and organization_id=p_organization_id) then raise exception using errcode='42501',message='SUBDIVISION_SALE_DRAFT_WORK_STATE_CONTEXT_DENIED';end if;insert into public.subdivision_sale_draft_work_states(organization_id,sale_draft_id,work_phase,updated_by)values(p_organization_id,p_sale_draft_id,p_work_phase,p_actor_user_id)on conflict(organization_id,sale_draft_id)do update set work_phase=excluded.work_phase,updated_by=excluded.updated_by,updated_at=now() returning id into v_state_id;insert into public.admin_audit_events(correlation_id,actor_user_id,organization_id,command_name,outcome,target_type,target_id,payload_redacted)values(p_correlation_id,p_actor_user_id,p_organization_id,'subdivision_upsert_sale_draft_work_state','allowed','subdivision_sale_draft_work_state',v_state_id,jsonb_build_object('module',p_module::text,'purpose_code',trim(p_purpose_code),'work_phase',p_work_phase));return v_state_id;end;$$;
revoke all on function public.subdivision_upsert_sale_draft_work_state(uuid,uuid,public.operating_module,text,uuid,text,uuid) from public,anon,authenticated;grant execute on function public.subdivision_upsert_sale_draft_work_state(uuid,uuid,public.operating_module,text,uuid,text,uuid) to service_role;
create or replace function public.subdivision_list_sale_draft_work_states(p_actor_user_id uuid,p_organization_id uuid,p_module public.operating_module,p_purpose_code text) returns table(sale_draft_work_state_id uuid,sale_draft_id uuid,work_phase text,updated_at timestamptz) language plpgsql security definer set search_path='' as $$ begin perform private.require_subdivision_draft_authority(p_actor_user_id,p_organization_id,p_module,p_purpose_code);return query select id,sale_draft_id,work_phase,updated_at from public.subdivision_sale_draft_work_states where organization_id=p_organization_id order by updated_at desc;end;$$;
revoke all on function public.subdivision_list_sale_draft_work_states(uuid,uuid,public.operating_module,text) from public,anon,authenticated;grant execute on function public.subdivision_list_sale_draft_work_states(uuid,uuid,public.operating_module,text) to service_role;
